<?php

namespace App\Services\Operation;

use App\Core\BaseService;
use App\Exceptions\ConflictApiException;
use App\Exceptions\NotFoundApiException;
use App\Exceptions\TenantAccessDeniedException;
use App\Libraries\ListQuery;
use App\Models\AssetModel;
use Config\Database;
use Throwable;

class AssetService extends BaseService
{
    public function __construct(private readonly AssetModel $model = new AssetModel()) { parent::__construct(); }
    public function list(array $query): array { $q=ListQuery::normalize($query,['sortable'=>['id','asset_no','asset_type','status','created_at'],'filterable'=>['site_id','block_id','unit_id','asset_type','status']]); $b=$this->model->builder()->select('*')->where('deleted_at',null); foreach($q['filters'] as $f=>$v){$b->where($f,$v);} if($q['search']!==''){$b->groupStart()->like('asset_no',$q['search'])->orLike('name',$q['search'])->groupEnd();} $t=(int)$b->countAllResults(false); $i=$b->orderBy($q['sort'],$q['direction'])->limit($q['per_page'],($q['page']-1)*$q['per_page'])->get()->getResultArray(); return ListQuery::envelope($q['page'],$q['per_page'],$t,$i);}
    public function show(int $id): array { $this->assertAccessible($id); $r=$this->model->tenantFind($id); if(!is_array($r)){throw new NotFoundApiException('Asset bulunamadi');} return $r; }
    public function create(array $payload): array { $d=$this->normalize($payload); $this->assertSiteBlockUnit($d['site_id'],$d['block_id'],$d['unit_id']); $this->assertUnique($d['asset_no'],$d['serial_number'],null); $this->model->insert($d,true); $id=(int)$this->model->getInsertID(); $c=$this->show($id); $this->audit('operation.asset.create.success',['entity_type'=>'asset','entity_id'=>$id,'new_values'=>$c]); return $c; }
    public function update(int $id,array $payload): array { $old=$this->show($id); if((string)$old['status']==='retired'){throw new ConflictApiException('retired asset guncellenemez');} if(array_key_exists('status',$payload)&& (string)$payload['status']==='retired'){throw new ConflictApiException('asset emekliligi status endpoint disinda desteklenmez');} $d=$this->normalize($payload,$old); $this->assertSiteBlockUnit((int)$d['site_id'],$d['block_id']!==null?(int)$d['block_id']:null,$d['unit_id']!==null?(int)$d['unit_id']:null); $this->assertUnique((string)$d['asset_no'],$d['serial_number']!==null?(string)$d['serial_number']:null,$id); $this->model->update($id,$d); $n=$this->show($id); $this->audit('operation.asset.update.success',['entity_type'=>'asset','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function delete(int $id): void { $old=$this->show($id); $this->model->delete($id); $this->audit('operation.asset.delete.success',['entity_type'=>'asset','entity_id'=>$id,'old_values'=>$old]); }
    /** @return array<string,mixed> */ public function assertAssetUsable(int $id): array { $a=$this->show($id); if((string)$a['status']==='retired'){throw new ConflictApiException('retired asset icin islem yapilamaz');} return $a; }
    /** @return array<string,mixed> */ private function normalize(array $payload,array $cur=[]): array { $assetNo=array_key_exists('asset_no',$payload)?trim((string)$payload['asset_no']):((string)($cur['asset_no']??'')); if($assetNo===''){ $assetNo=$this->generateAssetNo(); } return ['site_id'=>(int)($payload['site_id']??$cur['site_id']??0),'block_id'=>array_key_exists('block_id',$payload)?($payload['block_id']===''||$payload['block_id']===null?null:(int)$payload['block_id']):($cur['block_id']??null),'unit_id'=>array_key_exists('unit_id',$payload)?($payload['unit_id']===''||$payload['unit_id']===null?null:(int)$payload['unit_id']):($cur['unit_id']??null),'asset_no'=>$assetNo,'asset_type'=>(string)($payload['asset_type']??$cur['asset_type']??''),'name'=>trim((string)($payload['name']??$cur['name']??'')),'brand'=>array_key_exists('brand',$payload)?(($payload['brand']??'')===''?null:trim((string)$payload['brand'])):($cur['brand']??null),'model'=>array_key_exists('model',$payload)?(($payload['model']??'')===''?null:trim((string)$payload['model'])):($cur['model']??null),'serial_number'=>array_key_exists('serial_number',$payload)?(($payload['serial_number']??'')===''?null:trim((string)$payload['serial_number'])):($cur['serial_number']??null),'purchase_date'=>$payload['purchase_date']??($cur['purchase_date']??null),'warranty_until'=>$payload['warranty_until']??($cur['warranty_until']??null),'location_note'=>array_key_exists('location_note',$payload)?(($payload['location_note']??'')===''?null:trim((string)$payload['location_note'])):($cur['location_note']??null),'status'=>(string)($payload['status']??$cur['status']??'active')]; }
    private function assertSiteBlockUnit(int $siteId,?int $blockId,?int $unitId): void { $db=Database::connect(); $ctx=(int)(service('request')->company_id??0); $s=$db->table('sites')->where('id',$siteId)->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($s)){throw new NotFoundApiException('Site bulunamadi');} if($ctx>0 && (int)$s['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} if($blockId!==null){$b=$db->table('blocks')->where('id',$blockId)->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($b)){throw new NotFoundApiException('Block bulunamadi');} if((int)$b['site_id']!==$siteId){throw new ConflictApiException('block.site_id uyumsuz');} if($ctx>0 && (int)$b['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');}} if($unitId!==null){ if($blockId===null){throw new ConflictApiException('unit_id verildiginde block_id zorunludur');} $u=$db->table('units')->where('id',$unitId)->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($u)){throw new NotFoundApiException('Unit bulunamadi');} if((int)$u['site_id']!==$siteId || (int)$u['block_id']!==$blockId){throw new ConflictApiException('unit.site/block uyumsuz');} if($ctx>0 && (int)$u['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');}} }
    private function assertUnique(string $assetNo,?string $serialNumber,?int $exceptId): void { $ctx=(int)(service('request')->company_id??0); $b=$this->model->builder()->select('id')->where('company_id',$ctx)->where('asset_no',$assetNo)->where('deleted_at',null); if($exceptId!==null){$b->where('id !=',$exceptId);} if($b->get(1)->getRowArray()!==null){throw new ConflictApiException('asset_no unique olmali');} if($serialNumber!==null && $serialNumber!==''){ $sb=$this->model->builder()->select('id')->where('company_id',$ctx)->where('serial_number',$serialNumber)->where('deleted_at',null)->whereIn('status',['active','maintenance','broken']); if($exceptId!==null){$sb->where('id !=',$exceptId);} if($sb->get(1)->getRowArray()!==null){throw new ConflictApiException('aktif asset icin serial_number duplicate olamaz');}} }
    private function assertAccessible(int $id): void { $r=Database::connect()->table('assets')->where('id',$id)->get(1)->getRowArray(); if(!is_array($r)||($r['deleted_at']??null)!==null){throw new NotFoundApiException('Asset bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0 && (int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} }
    private function generateAssetNo(): string { for($i=0;$i<5;$i++){ $no='AST-'.date('YmdHis').'-'.strtoupper(substr(bin2hex(random_bytes(3)),0,6)); try{$this->assertUnique($no,null,null); return $no;}catch(Throwable){}} throw new ConflictApiException('asset_no uretilemedi'); }
}
