<?php

namespace App\Services\Operation;

use App\Core\BaseService;
use App\Exceptions\ConflictApiException;
use App\Exceptions\NotFoundApiException;
use App\Exceptions\TenantAccessDeniedException;
use App\Libraries\ListQuery;
use App\Models\AssetMaintenancePlanModel;
use Config\Database;

class AssetMaintenancePlanService extends BaseService
{
    public function __construct(private readonly AssetMaintenancePlanModel $model = new AssetMaintenancePlanModel(), private readonly AssetService $assetService = new AssetService()) { parent::__construct(); }
    public function list(array $query): array { $q=ListQuery::normalize($query,['sortable'=>['id','next_due_date','status','created_at'],'filterable'=>['asset_id','status','frequency_type']]); $b=$this->model->builder()->select('*')->where('deleted_at',null); foreach($q['filters'] as $f=>$v){$b->where($f,$v);} $t=(int)$b->countAllResults(false); $i=$b->orderBy($q['sort'],$q['direction'])->limit($q['per_page'],($q['page']-1)*$q['per_page'])->get()->getResultArray(); return ListQuery::envelope($q['page'],$q['per_page'],$t,$i);}
    public function show(int $id): array { $this->assertAccessible($id); $r=$this->model->tenantFind($id); if(!is_array($r)){throw new NotFoundApiException('Plan bulunamadi');} return $r; }
    public function create(array $payload): array { $asset=$this->assetService->assertAssetUsable((int)$payload['asset_id']); if(!in_array((string)$asset['status'],['active','maintenance','broken'],true)){throw new ConflictApiException('Bu asset statusu icin plan olusturulamaz');} $d=$this->normalize($payload); $this->assertPlanDates($d); $this->model->insert($d,true); $id=(int)$this->model->getInsertID(); $c=$this->show($id); $this->audit('operation.asset_maintenance_plan.create.success',['entity_type'=>'asset_maintenance_plan','entity_id'=>$id,'new_values'=>$c]); return $c; }
    public function update(int $id,array $payload): array { $old=$this->show($id); if((string)$old['status']==='cancelled'){throw new ConflictApiException('cancelled plan guncellenemez');} if(array_key_exists('status',$payload) && (string)$payload['status']!==(string)$old['status']){throw new ConflictApiException('plan status degisimi pause/resume/cancel endpointleriyle yapilmali');} $d=$this->normalize($payload,$old); $this->assertPlanDates($d); $this->model->update($id,$d); $n=$this->show($id); $this->audit('operation.asset_maintenance_plan.update.success',['entity_type'=>'asset_maintenance_plan','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function pause(int $id): array { $old=$this->show($id); if((string)$old['status']!=='active'){throw new ConflictApiException('pause sadece active icin calisir');} $this->model->update($id,['status'=>'paused']); $n=$this->show($id); $this->audit('operation.asset_maintenance_plan.pause.success',['entity_type'=>'asset_maintenance_plan','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function resume(int $id): array { $old=$this->show($id); if((string)$old['status']!=='paused'){throw new ConflictApiException('resume sadece paused icin calisir');} $this->model->update($id,['status'=>'active']); $n=$this->show($id); $this->audit('operation.asset_maintenance_plan.resume.success',['entity_type'=>'asset_maintenance_plan','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function cancel(int $id): array { $old=$this->show($id); if(!in_array((string)$old['status'],['active','paused'],true)){throw new ConflictApiException('cancel active/paused icin calisir');} $this->model->update($id,['status'=>'cancelled']); $n=$this->show($id); $this->audit('operation.asset_maintenance_plan.cancel.success',['entity_type'=>'asset_maintenance_plan','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    /** @return array<string,mixed> */ public function assertPlanAccessible(int $id): array { $p=$this->show($id); if((string)$p['status']==='cancelled'){throw new ConflictApiException('cancelled plan kullanilamaz');} return $p; }
    /** @return array<string,mixed> */ private function normalize(array $payload,array $cur=[]): array { return ['asset_id'=>(int)($payload['asset_id']??$cur['asset_id']??0),'frequency_type'=>(string)($payload['frequency_type']??$cur['frequency_type']??''),'frequency_interval'=>(int)($payload['frequency_interval']??$cur['frequency_interval']??1),'next_due_date'=>(string)($payload['next_due_date']??$cur['next_due_date']??''),'vendor_name'=>array_key_exists('vendor_name',$payload)?(($payload['vendor_name']??'')===''?null:trim((string)$payload['vendor_name'])):($cur['vendor_name']??null),'notes'=>array_key_exists('notes',$payload)?(($payload['notes']??'')===''?null:trim((string)$payload['notes'])):($cur['notes']??null),'status'=>(string)($payload['status']??$cur['status']??'active')]; }
    /** @param array<string,mixed> $d */ private function assertPlanDates(array $d): void { if((int)$d['frequency_interval']<1){throw new ConflictApiException('frequency_interval 1den kucuk olamaz');} if(strtotime((string)$d['next_due_date'])<strtotime(date('Y-m-d'))){throw new ConflictApiException('next_due_date gecmis olamaz');} }
    private function assertAccessible(int $id): void { $r=Database::connect()->table('asset_maintenance_plans')->where('id',$id)->get(1)->getRowArray(); if(!is_array($r)||($r['deleted_at']??null)!==null){throw new NotFoundApiException('Plan bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0 && (int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} }
}
