<?php

namespace App\Services\Operation;

use App\Core\BaseService;
use App\Exceptions\ConflictApiException;
use App\Exceptions\NotFoundApiException;
use App\Exceptions\TenantAccessDeniedException;
use App\Libraries\ListQuery;
use App\Models\AssetMaintenanceRecordModel;
use Config\Database;

class AssetMaintenanceRecordService extends BaseService
{
    public function __construct(private readonly AssetMaintenanceRecordModel $model = new AssetMaintenanceRecordModel(), private readonly AssetService $assetService = new AssetService(), private readonly AssetMaintenancePlanService $planService = new AssetMaintenancePlanService()) { parent::__construct(); }
    public function list(array $query): array { $q=ListQuery::normalize($query,['sortable'=>['id','performed_at','status','created_at'],'filterable'=>['asset_id','maintenance_plan_id','status']]); $b=$this->model->builder()->select('*')->where('deleted_at',null); foreach($q['filters'] as $f=>$v){$b->where($f,$v);} $t=(int)$b->countAllResults(false); $i=$b->orderBy($q['sort'],$q['direction'])->limit($q['per_page'],($q['page']-1)*$q['per_page'])->get()->getResultArray(); return ListQuery::envelope($q['page'],$q['per_page'],$t,$i);}
    public function show(int $id): array { $this->assertAccessible($id); $r=$this->model->tenantFind($id); if(!is_array($r)){throw new NotFoundApiException('Record bulunamadi');} return $r; }
    public function create(array $payload): array { $asset=$this->assetService->assertAssetUsable((int)$payload['asset_id']); $planId=$payload['maintenance_plan_id']??null; if($planId!==null && $planId!==''){ $plan=$this->planService->assertPlanAccessible((int)$planId); if((int)$plan['asset_id']!==(int)$asset['id']){throw new ConflictApiException('maintenance_plan_id ayni assete ait olmali');}} $woId=$payload['work_order_id']??null; if($woId!==null && $woId!==''){ $wo=Database::connect()->table('work_orders')->where('id',(int)$woId)->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($wo)){throw new NotFoundApiException('Work order bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0 && (int)$wo['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');}} if(isset($payload['cost_amount']) && $payload['cost_amount']!==null && (float)$payload['cost_amount']<0){throw new ConflictApiException('cost_amount negatif olamaz');} $d=['asset_id'=>(int)$asset['id'],'maintenance_plan_id'=>$planId!==null&&$planId!==''?(int)$planId:null,'work_order_id'=>$woId!==null&&$woId!==''?(int)$woId:null,'performed_at'=>(string)$payload['performed_at'],'performed_by'=>isset($payload['performed_by'])&&$payload['performed_by']!==''?(string)$payload['performed_by']:null,'vendor_name'=>isset($payload['vendor_name'])&&$payload['vendor_name']!==''?(string)$payload['vendor_name']:null,'cost_amount'=>$payload['cost_amount']??null,'currency'=>(string)($payload['currency']??'TRY'),'description'=>isset($payload['description'])&&$payload['description']!==''?(string)$payload['description']:null,'next_due_date'=>$payload['next_due_date']??null,'status'=>(string)($payload['status']??'completed')]; $this->model->insert($d,true); $id=(int)$this->model->getInsertID(); if(in_array((string)$asset['status'],['maintenance','broken'],true)){ $this->assetService->update((int)$asset['id'],['status'=>'active']); } $c=$this->show($id); $this->audit('operation.asset_maintenance_record.create.success',['entity_type'=>'asset_maintenance_record','entity_id'=>$id,'new_values'=>$c]); return $c; }
    public function cancel(int $id): array { $old=$this->show($id); if((string)$old['status']==='cancelled'){throw new ConflictApiException('cancelled record tekrar cancel edilemez');} $this->model->update($id,['status'=>'cancelled']); $n=$this->show($id); $this->audit('operation.asset_maintenance_record.cancel.success',['entity_type'=>'asset_maintenance_record','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    private function assertAccessible(int $id): void { $r=Database::connect()->table('asset_maintenance_records')->where('id',$id)->get(1)->getRowArray(); if(!is_array($r)||($r['deleted_at']??null)!==null){throw new NotFoundApiException('Record bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0 && (int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} }
}
