<?php
namespace App\Services\Operation;
use App\Core\BaseService;
use App\Exceptions\ConflictApiException;
use App\Exceptions\NotFoundApiException;
use App\Exceptions\TenantAccessDeniedException;
use App\Libraries\ListQuery;
use App\Models\DecisionBookEntryModel;
use Config\Database;
use Throwable;
class DecisionBookService extends BaseService
{
    public function __construct(private readonly DecisionBookEntryModel $model = new DecisionBookEntryModel(), private readonly MeetingService $meetingService = new MeetingService()) { parent::__construct(); }
    public function list(array $query): array { $q=ListQuery::normalize($query,['sortable'=>['id','decision_no','decision_date','status','created_at'],'filterable'=>['meeting_id','vote_result','status']]); $b=$this->model->builder()->select('*')->where('deleted_at',null); foreach($q['filters'] as $f=>$v){$b->where($f,$v);} if($q['search']!==''){$b->groupStart()->like('decision_no',$q['search'])->orLike('subject',$q['search'])->groupEnd();} $t=(int)$b->countAllResults(false); $i=$b->orderBy($q['sort'],$q['direction'])->limit($q['per_page'],($q['page']-1)*$q['per_page'])->get()->getResultArray(); return ListQuery::envelope($q['page'],$q['per_page'],$t,$i); }
    public function show(int $id): array { $r=Database::connect()->table('decision_book_entries')->where('id',$id)->get(1)->getRowArray(); if(!is_array($r)||($r['deleted_at']??null)!==null){throw new NotFoundApiException('Decision kaydi bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0&&(int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} return $r; }
    public function create(array $payload): array { $d=$this->normalize($payload); $d['decision_no']=$this->generateDecisionNo(); $this->assertReferences($d); $this->model->insert($d,true); $id=(int)$this->model->getInsertID(); $n=$this->show($id); $this->audit('governance.decision_book.create.success',['entity_type'=>'decision_book_entry','entity_id'=>$id,'new_values'=>$n]); return $n; }
    public function update(int $id,array $payload): array { $old=$this->show($id); if(in_array((string)$old['status'],['locked','cancelled'],true)){throw new ConflictApiException('locked/cancelled decision update edilemez');} $d=$this->normalize($payload,$old); $this->assertReferences($d); $this->model->update($id,$d); $n=$this->show($id); $this->audit('governance.decision_book.update.success',['entity_type'=>'decision_book_entry','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function approve(int $id): array { $old=$this->show($id); if((string)$old['status']!=='draft'){throw new ConflictApiException('approve sadece draft icin calisir');} $this->model->update($id,['status'=>'approved']); $n=$this->show($id); $this->audit('governance.decision_book.approve.success',['entity_type'=>'decision_book_entry','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function lock(int $id): array { $old=$this->show($id); if((string)$old['status']!=='approved'){throw new ConflictApiException('lock sadece approved icin calisir');} $this->model->update($id,['status'=>'locked','locked_at'=>date('Y-m-d H:i:s')]); $n=$this->show($id); $this->audit('governance.decision_book.lock.success',['entity_type'=>'decision_book_entry','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function cancel(int $id): array { $old=$this->show($id); if(!in_array((string)$old['status'],['draft','approved'],true)){throw new ConflictApiException('cancel sadece draft/approved icin calisir');} $this->model->update($id,['status'=>'cancelled']); $n=$this->show($id); $this->audit('governance.decision_book.cancel.success',['entity_type'=>'decision_book_entry','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    /** @return array<string,mixed> */ private function normalize(array $p,array $c=[]): array { return ['meeting_id'=>array_key_exists('meeting_id',$p)?($p['meeting_id']===''||$p['meeting_id']===null?null:(int)$p['meeting_id']):($c['meeting_id']??null),'decision_date'=>(string)($p['decision_date']??$c['decision_date']??''),'subject'=>trim((string)($p['subject']??$c['subject']??'')),'decision_text'=>(string)($p['decision_text']??$c['decision_text']??''),'vote_result'=>(string)($p['vote_result']??$c['vote_result']??''),'status'=>(string)($c['status']??'draft'),'document_id'=>array_key_exists('document_id',$p)?($p['document_id']===''||$p['document_id']===null?null:(int)$p['document_id']):($c['document_id']??null),'created_by'=>(int)(service('request')->user_id??$c['created_by']??0)?:null]; }
    /** @param array<string,mixed> $d */ private function assertReferences(array $d): void { $ctx=(int)(service('request')->company_id??0); $db=Database::connect(); if($d['meeting_id']!==null){$this->meetingService->show((int)$d['meeting_id']);} if($d['document_id']!==null){$doc=$db->table('documents')->where('id',(int)$d['document_id'])->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($doc)){throw new NotFoundApiException('Document bulunamadi');} if((int)$doc['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');}} }
    private function generateDecisionNo(): string { for($i=0;$i<5;$i++){ $no='DEC-'.date('YmdHis').'-'.strtoupper(substr(bin2hex(random_bytes(2)),0,4)); try{$this->assertDecisionNoUnique($no); return $no;}catch(Throwable){}} throw new ConflictApiException('decision_no uretilemedi'); }
    private function assertDecisionNoUnique(string $decisionNo): void { $ctx=(int)(service('request')->company_id??0); $r=$this->model->builder()->select('id')->where('company_id',$ctx)->where('decision_no',$decisionNo)->where('deleted_at',null)->get(1)->getRowArray(); if($r!==null){throw new ConflictApiException('decision_no unique olmali');} }
}
