<?php
namespace App\Services\Operation;
use App\Core\BaseService;
use App\Exceptions\ConflictApiException;
use App\Exceptions\NotFoundApiException;
use App\Exceptions\TenantAccessDeniedException;
use App\Libraries\ListQuery;
use App\Models\DocumentAccessRuleModel;
use Config\Database;
class DocumentAccessRuleService extends BaseService
{
    public function __construct(private readonly DocumentAccessRuleModel $model = new DocumentAccessRuleModel()) { parent::__construct(); }
    public function listByDocument(int $documentId,array $query=[]): array { $this->assertDocumentTenant($documentId); $q=ListQuery::normalize($query,['sortable'=>['id','rule_type','rule_value','permission','created_at'],'filterable'=>['rule_type','permission']]); $b=$this->model->builder()->select('*')->where('document_id',$documentId)->where('deleted_at',null); foreach($q['filters'] as $f=>$v){$b->where($f,$v);} $t=(int)$b->countAllResults(false); $i=$b->orderBy($q['sort'],$q['direction'])->limit($q['per_page'],($q['page']-1)*$q['per_page'])->get()->getResultArray(); return ListQuery::envelope($q['page'],$q['per_page'],$t,$i); }
    public function create(int $documentId,array $payload): array { $doc=$this->assertDocumentTenant($documentId); $d=['document_id'=>$documentId,'rule_type'=>(string)$payload['rule_type'],'rule_value'=>trim((string)$payload['rule_value']),'permission'=>(string)$payload['permission']]; $this->assertRuleTarget($d['rule_type'],$d['rule_value']); $this->assertDuplicate($documentId,$d['rule_type'],$d['rule_value'],$d['permission'],null); $this->model->insert($d,true); $id=(int)$this->model->getInsertID(); $n=$this->show($id); $this->audit('document.access_rule.create.success',['entity_type'=>'document_access_rule','entity_id'=>$id,'new_values'=>$n,'document_id'=>$documentId]); return $n; }
    public function delete(int $id): void { $old=$this->show($id); $this->model->delete($id); $this->audit('document.access_rule.delete.success',['entity_type'=>'document_access_rule','entity_id'=>$id,'old_values'=>$old,'document_id'=>$old['document_id']??null]); }
    public function show(int $id): array { $r=Database::connect()->table('document_access_rules')->where('id',$id)->get(1)->getRowArray(); if(!is_array($r)||($r['deleted_at']??null)!==null){throw new NotFoundApiException('Document access rule bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0&&(int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} return $r; }
    public function hasAccess(int $documentId,string $permission): bool { $doc=Database::connect()->table('documents')->where('id',$documentId)->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($doc)){return false;} $ruleCompanyId=(int)($doc['company_id']??0); $ctx=(int)(service('request')->company_id??0); $uid=(int)(service('request')->user_id??0); $perms=$permission==='view'?['view','download','manage']:($permission==='download'?['download','manage']:['manage']); $rows=Database::connect()->table('document_access_rules')->where('company_id',$ruleCompanyId)->where('document_id',$documentId)->where('deleted_at',null)->whereIn('permission',$perms)->get()->getResultArray(); foreach($rows as $r){ if($this->ruleMatches($r,$uid)){return true;} } return false; }
    private function ruleMatches(array $r,int $userId): bool { $db=Database::connect(); $ctx=(int)(service('request')->company_id??0); $type=(string)($r['rule_type']??''); $value=(string)($r['rule_value']??''); if($type==='user'){return $userId>0 && $value===(string)$userId;} if($type==='role'){ $roleRows=$db->query("SELECT roles.code,roles.id FROM user_roles JOIN roles ON roles.id = user_roles.role_id WHERE user_roles.company_id = ? AND user_roles.user_id = ? AND user_roles.deleted_at IS NULL AND roles.deleted_at IS NULL",[$ctx,$userId])->getResultArray(); foreach($roleRows as $rr){ if($value===(string)$rr['code'] || $value===(string)$rr['id']){return true;} } return false; } if($type==='resident'){ $rp=$db->table('resident_profiles')->where('company_id',$ctx)->where('user_id',$userId)->where('deleted_at',null)->get()->getRowArray(); return is_array($rp) && $value===(string)$rp['id']; } if($type==='unit'){ $rp=$db->table('resident_profiles')->where('company_id',$ctx)->where('user_id',$userId)->where('deleted_at',null)->get()->getRowArray(); if(!is_array($rp)){return false;} $occ=$db->table('unit_occupancies')->where('company_id',$ctx)->where('resident_profile_id',(int)$rp['id'])->where('unit_id',(int)$value)->where('status','active')->where('deleted_at',null)->get()->getRowArray(); return is_array($occ); } if($type==='site'){ $rp=$db->table('resident_profiles')->where('company_id',$ctx)->where('user_id',$userId)->where('deleted_at',null)->get()->getRowArray(); if(!is_array($rp)){return false;} $occ=$db->table('unit_occupancies')->where('company_id',$ctx)->where('resident_profile_id',(int)$rp['id'])->where('status','active')->where('deleted_at',null)->get()->getResultArray(); foreach($occ as $o){$u=$db->table('units')->where('id',(int)$o['unit_id'])->where('site_id',(int)$value)->where('deleted_at',null)->get(1)->getRowArray(); if(is_array($u)){return true;}} return false; } return false; }
    private function assertDocumentTenant(int $documentId): array { $doc=Database::connect()->table('documents')->where('id',$documentId)->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($doc)){throw new NotFoundApiException('Document bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0 && (int)$doc['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} return $doc; }
    private function assertRuleTarget(string $type,string $value): void { $db=Database::connect(); $ctx=(int)(service('request')->company_id??0); if($type==='role'){ $role=$db->table('roles')->groupStart()->where('code',$value)->orWhere('id',(int)$value)->groupEnd()->groupStart()->where('company_id',$ctx)->orWhere('company_id',null)->groupEnd()->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($role)){throw new NotFoundApiException('Role bulunamadi');} return; } if($type==='user'){ $u=$db->table('users')->where('id',(int)$value)->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($u)){throw new NotFoundApiException('User bulunamadi');} return; } if($type==='resident'){ $r=$db->table('resident_profiles')->where('id',(int)$value)->where('company_id',$ctx)->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($r)){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} return; } if($type==='unit'){ $u=$db->table('units')->where('id',(int)$value)->where('company_id',$ctx)->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($u)){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} return; } if($type==='site'){ $s=$db->table('sites')->where('id',(int)$value)->where('company_id',$ctx)->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($s)){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} return; } throw new ConflictApiException('rule_type gecersiz'); }
    private function assertDuplicate(int $documentId,string $type,string $value,string $permission,?int $exceptId): void { $b=$this->model->builder()->select('id')->where('document_id',$documentId)->where('rule_type',$type)->where('rule_value',$value)->where('permission',$permission)->where('deleted_at',null); if($exceptId!==null){$b->where('id !=',$exceptId);} if($b->get(1)->getRowArray()!==null){throw new ConflictApiException('Ayni access rule duplicate olamaz');} }
}
