<?php
namespace App\Services\Operation;
use App\Core\BaseService;
use App\Exceptions\ConflictApiException;
use App\Exceptions\NotFoundApiException;
use App\Exceptions\TenantAccessDeniedException;
use App\Libraries\ListQuery;
use App\Models\DocumentVersionModel;
use Config\Database;
class DocumentVersionService extends BaseService
{
    public function __construct(private readonly DocumentVersionModel $model = new DocumentVersionModel(), private readonly DocumentService $documentService = new DocumentService()) { parent::__construct(); }
    public function listByDocument(int $documentId,array $query=[]): array { $this->documentService->show($documentId,true); $q=ListQuery::normalize($query,['sortable'=>['id','version_no','created_at'],'filterable'=>['mime_type']]); $b=$this->model->builder()->select('*')->where('document_id',$documentId)->where('deleted_at',null); foreach($q['filters'] as $f=>$v){$b->where($f,$v);} $t=(int)$b->countAllResults(false); $i=$b->orderBy($q['sort'],$q['direction'])->limit($q['per_page'],($q['page']-1)*$q['per_page'])->get()->getResultArray(); return ListQuery::envelope($q['page'],$q['per_page'],$t,$i); }
    public function show(int $id): array { $r=Database::connect()->table('document_versions')->where('id',$id)->get(1)->getRowArray(); if(!is_array($r)||($r['deleted_at']??null)!==null){throw new NotFoundApiException('Document version bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0&&(int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} $this->documentService->show((int)$r['document_id'],true); return $r; }
    public function create(int $documentId,array $payload): array { $doc=$this->documentService->show($documentId,false); if((string)$doc['status']==='deleted'){throw new ConflictApiException('deleted document icin version eklenemez');} $ctx=(int)(service('request')->company_id??0); $id=$this->runCreateTransaction($ctx,$documentId,$payload); $n=$this->show($id); $auditNew=$n; $auditNew['file_path']='[masked]'; $this->audit('document.version.create.success',['entity_type'=>'document_version','entity_id'=>$id,'document_id'=>$documentId,'new_values'=>$auditNew]); return $n; }
    private function runCreateTransaction(int $companyId,int $documentId,array $payload): int { $db=Database::connect(); $db->transBegin(); try{ $doc=$db->query("SELECT id,company_id,status FROM documents WHERE id = ? AND deleted_at IS NULL FOR UPDATE",[$documentId])->getRowArray(); if(!is_array($doc)){throw new NotFoundApiException('Document bulunamadi');} if((int)$doc['company_id']!==$companyId){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} if((string)$doc['status']==='deleted'){throw new ConflictApiException('deleted document icin version eklenemez');} $max=(int)($db->query("SELECT COALESCE(MAX(version_no),0) AS m FROM document_versions WHERE company_id = ? AND document_id = ? AND deleted_at IS NULL FOR UPDATE",[$companyId,$documentId])->getRowArray()['m']??0); $checksum=trim((string)($payload['checksum']??'')); if($checksum!==''){ $dup=$db->query("SELECT id FROM document_versions WHERE company_id = ? AND document_id = ? AND checksum = ? AND deleted_at IS NULL FOR UPDATE",[$companyId,$documentId,$checksum])->getRowArray(); if(is_array($dup)){throw new ConflictApiException('Ayni checksum duplicate version olamaz');}} $data=['document_id'=>$documentId,'version_no'=>$max+1,'file_name'=>trim((string)$payload['file_name']),'file_path'=>trim((string)$payload['file_path']),'mime_type'=>($payload['mime_type']??'')===''?null:(string)$payload['mime_type'],'size_bytes'=>($payload['size_bytes']??'')===''?null:(int)$payload['size_bytes'],'checksum'=>$checksum===''?null:$checksum,'uploaded_by'=>(int)(service('request')->user_id??0)?:null]; $this->model->insert($data,true); $id=(int)$this->model->getInsertID(); if($db->transStatus()===false){throw new ConflictApiException('Version kaydi tamamlanamadi');} $db->transCommit(); return $id; }catch(\Throwable $e){$db->transRollback(); if($e instanceof ConflictApiException||$e instanceof NotFoundApiException||$e instanceof TenantAccessDeniedException){throw $e;} throw new ConflictApiException('Version olusturma islemi tamamlanamadi');} }
}
