<?php
namespace App\Services\Operation;
use App\Core\BaseService;
use App\Exceptions\ConflictApiException;
use App\Exceptions\NotFoundApiException;
use App\Exceptions\TenantAccessDeniedException;
use App\Libraries\ListQuery;
use App\Models\DocumentModel;
use Config\Database;
class DocumentService extends BaseService
{
    public function __construct(private readonly DocumentModel $model = new DocumentModel(), private readonly DocumentCategoryService $categoryService = new DocumentCategoryService(), private readonly DocumentAccessRuleService $ruleService = new DocumentAccessRuleService()) { parent::__construct(); }
    public function list(array $query): array { $q=ListQuery::normalize($query,['sortable'=>['id','title','document_type','visibility','status','created_at'],'filterable'=>['category_id','site_id','unit_id','resident_profile_id','staff_profile_id','document_type','visibility','status']]); $b=$this->model->builder()->select('*')->where('deleted_at',null); foreach($q['filters'] as $f=>$v){$b->where($f,$v);} if($q['search']!==''){$b->groupStart()->like('title',$q['search'])->orLike('description',$q['search'])->groupEnd();} $all=$b->orderBy($q['sort'],$q['direction'])->get()->getResultArray(); $visible=array_values(array_filter($all,fn(array $r): bool=>$this->canViewDocument($r))); $total=count($visible); $offset=($q['page']-1)*$q['per_page']; $items=array_slice($visible,$offset,$q['per_page']); return ListQuery::envelope($q['page'],$q['per_page'],$total,$items); }
    public function show(int $id,bool $enforceView=true): array { $r=Database::connect()->table('documents')->where('id',$id)->get(1)->getRowArray(); if(!is_array($r)||($r['deleted_at']??null)!==null){throw new NotFoundApiException('Document bulunamadi');} $ctx=(int)(service('request')->company_id??0); $docCompany=(int)($r['company_id']??0); if($ctx>0 && $docCompany!==$ctx){ $vis=(string)($r['visibility']??'private'); if($vis==='public' || $vis==='management'){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} } if($enforceView && !$this->canViewDocument($r)){throw new TenantAccessDeniedException('Belgeye erisim yetkiniz yok');} return $r; }
    public function create(array $payload): array { $d=$this->normalize($payload); $this->assertReferences($d); $this->model->insert($d,true); $id=(int)$this->model->getInsertID(); $n=$this->show($id,false); $this->audit('document.document.create.success',['entity_type'=>'document','entity_id'=>$id,'new_values'=>$n]); return $n; }
    public function update(int $id,array $payload): array { $old=$this->loadForMutation($id); if((string)($old['status']??'')==='deleted' || ($old['deleted_at']??null)!==null){throw new ConflictApiException('deleted document update edilemez');} if((string)$old['status']==='archived'){throw new ConflictApiException('archived document update edilemez');} $d=$this->normalize($payload,$old); $this->assertReferences($d); $this->model->update($id,$d); $n=$this->show($id,false); $this->audit('document.document.update.success',['entity_type'=>'document','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function archive(int $id): array { $old=$this->loadForMutation($id); if((string)($old['status']??'')==='deleted' || ($old['deleted_at']??null)!==null){throw new ConflictApiException('deleted document archive edilemez');} if((string)$old['status']!=='active'){throw new ConflictApiException('archive sadece active document icin calisir');} $this->model->update($id,['status'=>'archived']); $n=$this->show($id,false); $this->audit('document.document.archive.success',['entity_type'=>'document','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function restore(int $id): array { $old=$this->loadForMutation($id); if((string)($old['status']??'')==='deleted' || ($old['deleted_at']??null)!==null){throw new ConflictApiException('deleted document restore edilemez');} if((string)$old['status']!=='archived'){throw new ConflictApiException('restore sadece archived document icin calisir');} $this->model->update($id,['status'=>'active']); $n=$this->show($id,false); $this->audit('document.document.restore.success',['entity_type'=>'document','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function delete(int $id): void { $old=$this->loadForMutation($id); if((string)($old['status']??'')==='deleted' || ($old['deleted_at']??null)!==null){throw new ConflictApiException('document zaten deleted');} $this->model->update($id,['status'=>'deleted']); $this->model->delete($id); $new=['id'=>$id,'status'=>'deleted']; $this->audit('document.document.delete.success',['entity_type'=>'document','entity_id'=>$id,'old_values'=>$old,'new_values'=>$new]); }
    /** @param array<string,mixed> $doc */ public function canViewDocument(array $doc): bool { $uid=(int)(service('request')->user_id??0); $ctx=(int)(service('request')->company_id??0); $docCompany=(int)($doc['company_id']??0); $sameTenant=$ctx<=0||$docCompany===$ctx; $vis=(string)($doc['visibility']??'private'); if($vis==='public'){return true;} if($sameTenant && $this->isManagementUser($uid)){return true;} if($vis==='private'){return $this->ruleService->hasAccess((int)$doc['id'],'view');} if($vis==='management'){return $sameTenant && $this->isStaffUser($uid);} if($vis==='residents'){return ($sameTenant && $this->isResidentRelated($uid,$doc)) || $this->ruleService->hasAccess((int)$doc['id'],'view');} return false; }
    /** @return array<string,mixed> */ private function normalize(array $p,array $c=[]): array { return ['category_id'=>array_key_exists('category_id',$p)?($p['category_id']===''||$p['category_id']===null?null:(int)$p['category_id']):($c['category_id']??null),'site_id'=>array_key_exists('site_id',$p)?($p['site_id']===''||$p['site_id']===null?null:(int)$p['site_id']):($c['site_id']??null),'block_id'=>array_key_exists('block_id',$p)?($p['block_id']===''||$p['block_id']===null?null:(int)$p['block_id']):($c['block_id']??null),'unit_id'=>array_key_exists('unit_id',$p)?($p['unit_id']===''||$p['unit_id']===null?null:(int)$p['unit_id']):($c['unit_id']??null),'resident_profile_id'=>array_key_exists('resident_profile_id',$p)?($p['resident_profile_id']===''||$p['resident_profile_id']===null?null:(int)$p['resident_profile_id']):($c['resident_profile_id']??null),'staff_profile_id'=>array_key_exists('staff_profile_id',$p)?($p['staff_profile_id']===''||$p['staff_profile_id']===null?null:(int)$p['staff_profile_id']):($c['staff_profile_id']??null),'title'=>trim((string)($p['title']??$c['title']??'')),'description'=>array_key_exists('description',$p)?(($p['description']??'')===''?null:trim((string)$p['description'])):($c['description']??null),'document_type'=>(string)($p['document_type']??$c['document_type']??'other'),'visibility'=>(string)($p['visibility']??$c['visibility']??'private'),'status'=>(string)($p['status']??$c['status']??'active'),'created_by'=>(int)(service('request')->user_id??$c['created_by']??0)?:null]; }
    /** @param array<string,mixed> $d */ private function assertReferences(array $d): void { $db=Database::connect(); $ctx=(int)(service('request')->company_id??0); if($d['category_id']!==null){$this->categoryService->show((int)$d['category_id']);} if($d['site_id']!==null){$s=$db->table('sites')->where('id',(int)$d['site_id'])->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($s)){throw new NotFoundApiException('Site bulunamadi');} if((int)$s['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');}} if($d['block_id']!==null){$b=$db->table('blocks')->where('id',(int)$d['block_id'])->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($b)){throw new NotFoundApiException('Block bulunamadi');} if((int)$b['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} if($d['site_id']!==null && (int)$b['site_id']!==(int)$d['site_id']){throw new ConflictApiException('block.site_id uyumsuz');}} if($d['unit_id']!==null){$u=$db->table('units')->where('id',(int)$d['unit_id'])->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($u)){throw new NotFoundApiException('Unit bulunamadi');} if((int)$u['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} if($d['block_id']===null || $d['site_id']===null){throw new ConflictApiException('unit_id verildiginde block_id ve site_id zorunlu');} if((int)$u['block_id']!==(int)$d['block_id'] || (int)$u['site_id']!==(int)$d['site_id']){throw new ConflictApiException('unit/block/site uyumsuz');}} if($d['resident_profile_id']!==null){$r=$db->table('resident_profiles')->where('id',(int)$d['resident_profile_id'])->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($r)){throw new NotFoundApiException('Resident bulunamadi');} if((int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} if($d['unit_id']!==null){$occ=$db->table('unit_occupancies')->where('company_id',$ctx)->where('unit_id',(int)$d['unit_id'])->where('resident_profile_id',(int)$d['resident_profile_id'])->where('status','active')->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($occ)){throw new ConflictApiException('resident unit ile aktif occupancy iliskisinde olmali');}} } if($d['staff_profile_id']!==null){$s=$db->table('staff_profiles')->where('id',(int)$d['staff_profile_id'])->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($s)){throw new NotFoundApiException('Staff profile bulunamadi');} if((int)$s['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');}} }
    private function isManagementUser(int $userId): bool { if($userId<=0){return false;} $ctx=(int)(service('request')->company_id??0); $rows=Database::connect()->query("SELECT roles.code FROM user_roles JOIN roles ON roles.id = user_roles.role_id WHERE user_roles.company_id = ? AND user_roles.user_id = ? AND user_roles.deleted_at IS NULL AND roles.deleted_at IS NULL",[$ctx,$userId])->getResultArray(); foreach($rows as $r){if(in_array((string)$r['code'],['company_admin','super_admin'],true)){return true;}} return false; }
    private function isStaffUser(int $userId): bool { if($userId<=0){return false;} $ctx=(int)(service('request')->company_id??0); $rows=Database::connect()->query("SELECT roles.code FROM user_roles JOIN roles ON roles.id = user_roles.role_id WHERE user_roles.company_id = ? AND user_roles.user_id = ? AND user_roles.deleted_at IS NULL AND roles.deleted_at IS NULL",[$ctx,$userId])->getResultArray(); foreach($rows as $r){if(in_array((string)$r['code'],['company_admin','employee','super_admin'],true)){return true;}} return false; }
    /** @param array<string,mixed> $doc */ private function isResidentRelated(int $userId,array $doc): bool { if($userId<=0){return false;} $ctx=(int)(service('request')->company_id??0); $db=Database::connect(); $rp=$db->table('resident_profiles')->where('company_id',$ctx)->where('user_id',$userId)->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($rp)){return false;} if(($doc['resident_profile_id']??null)!==null && (int)$doc['resident_profile_id']===(int)$rp['id']){return true;} if(($doc['unit_id']??null)!==null){$occ=$db->table('unit_occupancies')->where('company_id',$ctx)->where('resident_profile_id',(int)$rp['id'])->where('unit_id',(int)$doc['unit_id'])->where('status','active')->where('deleted_at',null)->get(1)->getRowArray(); return is_array($occ);} return false; }
    private function loadForMutation(int $id): array { $r=Database::connect()->table('documents')->where('id',$id)->get(1)->getRowArray(); if(!is_array($r)){throw new NotFoundApiException('Document bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0&&(int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} return $r; }
}
