<?php
namespace App\Services\Operation;
use App\Core\BaseService;
use App\Exceptions\ConflictApiException;
use App\Exceptions\NotFoundApiException;
use App\Exceptions\TenantAccessDeniedException;
use App\Libraries\ListQuery;
use App\Models\LegalCaseModel;
use Config\Database;
use Throwable;
class LegalCaseService extends BaseService
{
    public function __construct(private readonly LegalCaseModel $model = new LegalCaseModel()) { parent::__construct(); }
    public function list(array $query): array { $q=ListQuery::normalize($query,['sortable'=>['id','case_no','case_type','status','total_amount','created_at'],'filterable'=>['site_id','unit_id','resident_profile_id','case_type','status']]); $b=$this->model->builder()->select('*')->where('deleted_at',null); foreach($q['filters'] as $f=>$v){$b->where($f,$v);} if($q['search']!==''){$b->groupStart()->like('case_no',$q['search'])->orLike('lawyer_name',$q['search'])->groupEnd();} $t=(int)$b->countAllResults(false); $i=$b->orderBy($q['sort'],$q['direction'])->limit($q['per_page'],($q['page']-1)*$q['per_page'])->get()->getResultArray(); return ListQuery::envelope($q['page'],$q['per_page'],$t,$i); }
    public function show(int $id): array { $r=Database::connect()->table('legal_cases')->where('id',$id)->get(1)->getRowArray(); if(!is_array($r)||($r['deleted_at']??null)!==null){throw new NotFoundApiException('Legal case bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0&&(int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} return $r; }
    public function create(array $payload): array { $d=$this->normalize($payload); $this->assertReferences($d); $d['case_no']=$this->generateCaseNo(); $d['status']='draft'; $this->model->insert($d,true); $id=(int)$this->model->getInsertID(); $n=$this->show($id); $this->audit('legal.legal_case.create.success',['entity_type'=>'legal_case','entity_id'=>$id,'new_values'=>$n]); return $n; }
    public function update(int $id,array $payload): array { $old=$this->show($id); if(in_array((string)$old['status'],['closed','cancelled'],true)){throw new ConflictApiException('closed/cancelled case update edilemez');} $d=$this->normalize($payload,$old); if(array_key_exists('status',$payload) && $payload['status']!==null && $payload['status']!==''){ $next=(string)$payload['status']; $current=(string)$old['status']; if(!($current==='draft' && $next==='prepared') && !($current==='filed' && $next==='in_progress')){ throw new ConflictApiException('status transition gecersiz'); } $d['status']=$next; } $this->assertReferences($d); $this->model->update($id,$d); $n=$this->show($id); $this->audit('legal.legal_case.update.success',['entity_type'=>'legal_case','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function sendToLawyer(int $id): array { $old=$this->show($id); if((string)$old['status']!=='prepared'){throw new ConflictApiException('send-to-lawyer sadece prepared icin calisir');} return $this->transition($id,$old,'sent_to_lawyer','legal.legal_case.send_to_lawyer.success'); }
    public function file(int $id): array { $old=$this->show($id); if((string)$old['status']!=='sent_to_lawyer'){throw new ConflictApiException('file sadece sent_to_lawyer icin calisir');} return $this->transition($id,$old,'filed','legal.legal_case.file.success'); }
    public function markPaid(int $id): array { $old=$this->show($id); if((string)$old['status']!=='in_progress'){throw new ConflictApiException('mark-paid sadece in_progress icin calisir');} return $this->transition($id,$old,'paid','legal.legal_case.mark_paid.success'); }
    public function close(int $id): array { $old=$this->show($id); if((string)$old['status']!=='paid'){throw new ConflictApiException('close sadece paid icin calisir');} $this->model->update($id,['status'=>'closed','closed_at'=>date('Y-m-d H:i:s')]); $n=$this->show($id); $this->audit('legal.legal_case.close.success',['entity_type'=>'legal_case','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function cancel(int $id): array { $old=$this->show($id); if((string)$old['status']==='closed'){throw new ConflictApiException('closed case cancel edilemez');} if(!in_array((string)$old['status'],['draft','prepared','sent_to_lawyer','filed','in_progress'],true)){throw new ConflictApiException('case cancel state gecersiz');} return $this->transition($id,$old,'cancelled','legal.legal_case.cancel.success'); }
    public function setPrepared(int $id): array { $old=$this->show($id); if((string)$old['status']!=='draft'){throw new ConflictApiException('prepared sadece drafttan gecer');} return $this->transition($id,$old,'prepared','legal.legal_case.update.success'); }
    public function assertDebtMutable(int $id): array { $c=$this->show($id); if(in_array((string)$c['status'],['paid','closed','cancelled'],true)){throw new ConflictApiException('paid/cancelled/closed case debt degisikligine kapali');} return $c; }
    public function recalcTotals(int $id): void { $ctx=(int)(service('request')->company_id??0); $row=Database::connect()->query("SELECT COALESCE(SUM(principal_amount),0) AS p, COALESCE(SUM(interest_amount),0) AS i FROM legal_case_debts WHERE company_id = ? AND legal_case_id = ? AND deleted_at IS NULL AND status = 'active'",[$ctx,$id])->getRowArray(); $p=(float)($row['p']??0); $i=(float)($row['i']??0); $case=$this->show($id); $e=(float)($case['expense_amount']??0); $t=round($p+$i+$e,2); $this->model->update($id,['principal_amount'=>round($p,2),'interest_amount'=>round($i,2),'total_amount'=>$t]); }
    /** @return array<string,mixed> */ private function normalize(array $p,array $c=[]): array { return ['site_id'=>(int)($p['site_id']??$c['site_id']??0),'unit_id'=>array_key_exists('unit_id',$p)?($p['unit_id']===''||$p['unit_id']===null?null:(int)$p['unit_id']):($c['unit_id']??null),'resident_profile_id'=>array_key_exists('resident_profile_id',$p)?($p['resident_profile_id']===''||$p['resident_profile_id']===null?null:(int)$p['resident_profile_id']):($c['resident_profile_id']??null),'case_type'=>(string)($p['case_type']??$c['case_type']??''),'lawyer_name'=>array_key_exists('lawyer_name',$p)?(($p['lawyer_name']??'')===''?null:trim((string)$p['lawyer_name'])):($c['lawyer_name']??null),'enforcement_office'=>array_key_exists('enforcement_office',$p)?(($p['enforcement_office']??'')===''?null:trim((string)$p['enforcement_office'])):($c['enforcement_office']??null),'file_number'=>array_key_exists('file_number',$p)?(($p['file_number']??'')===''?null:trim((string)$p['file_number'])):($c['file_number']??null),'expense_amount'=>array_key_exists('expense_amount',$p)?(float)$p['expense_amount']:(float)($c['expense_amount']??0),'opened_at'=>array_key_exists('opened_at',$p)?(($p['opened_at']??'')===''?null:(string)$p['opened_at']):($c['opened_at']??null),'notes'=>array_key_exists('notes',$p)?(($p['notes']??'')===''?null:(string)$p['notes']):($c['notes']??null),'status'=>(string)($c['status']??'draft')]; }
    /** @param array<string,mixed> $d */ private function assertReferences(array $d): void { $db=Database::connect(); $ctx=(int)(service('request')->company_id??0); $site=$db->table('sites')->where('id',(int)$d['site_id'])->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($site)){throw new NotFoundApiException('Site bulunamadi');} if((int)$site['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} if($d['unit_id']!==null){$u=$db->table('units')->where('id',(int)$d['unit_id'])->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($u)){throw new NotFoundApiException('Unit bulunamadi');} if((int)$u['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} if((int)$u['site_id']!==(int)$d['site_id']){throw new ConflictApiException('unit.site case.site ile uyumsuz');}} if($d['resident_profile_id']!==null){$r=$db->table('resident_profiles')->where('id',(int)$d['resident_profile_id'])->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($r)){throw new NotFoundApiException('Resident bulunamadi');} if((int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} if($d['unit_id']!==null){$occ=$db->table('unit_occupancies')->where('company_id',$ctx)->where('unit_id',(int)$d['unit_id'])->where('resident_profile_id',(int)$d['resident_profile_id'])->where('status','active')->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($occ)){throw new ConflictApiException('resident unit ile aktif occupancy iliskisinde olmali');}} } }
    private function generateCaseNo(): string { for($i=0;$i<5;$i++){ $no='LGL-'.date('YmdHis').'-'.strtoupper(substr(bin2hex(random_bytes(2)),0,4)); try{$this->assertCaseNoUnique($no); return $no;}catch(Throwable){}} throw new ConflictApiException('case_no uretilemedi'); }
    private function assertCaseNoUnique(string $caseNo): void { $ctx=(int)(service('request')->company_id??0); $r=$this->model->builder()->select('id')->where('company_id',$ctx)->where('case_no',$caseNo)->where('deleted_at',null)->get(1)->getRowArray(); if($r!==null){throw new ConflictApiException('case_no unique olmali');} }
    private function transition(int $id,array $old,string $next,string $event): array { $update=['status'=>$next]; if($next==='cancelled'){$update['closed_at']=null;} if($next==='paid'){$update['closed_at']=null;} $this->model->update($id,$update); $n=$this->show($id); $this->audit($event,['entity_type'=>'legal_case','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
}
