<?php
namespace App\Services\Operation;
use App\Core\BaseService;
use App\Exceptions\ConflictApiException;
use App\Exceptions\NotFoundApiException;
use App\Exceptions\TenantAccessDeniedException;
use App\Libraries\ListQuery;
use App\Models\LegalCaseDebtModel;
use Config\Database;
class LegalCaseDebtService extends BaseService
{
    public function __construct(private readonly LegalCaseDebtModel $model = new LegalCaseDebtModel(), private readonly LegalCaseService $caseService = new LegalCaseService()) { parent::__construct(); }
    public function listByCase(int $caseId,array $query=[]): array { $this->caseService->show($caseId); $q=ListQuery::normalize($query,['sortable'=>['id','due_item_id','total_amount','status','created_at'],'filterable'=>['status']]); $b=$this->model->builder()->select('*')->where('legal_case_id',$caseId)->where('deleted_at',null); foreach($q['filters'] as $f=>$v){$b->where($f,$v);} $t=(int)$b->countAllResults(false); $i=$b->orderBy($q['sort'],$q['direction'])->limit($q['per_page'],($q['page']-1)*$q['per_page'])->get()->getResultArray(); return ListQuery::envelope($q['page'],$q['per_page'],$t,$i); }
    public function create(int $caseId,array $payload): array { $case=$this->caseService->assertDebtMutable($caseId); return $this->runDebtTransaction($caseId,function() use($case,$payload): array { $d=$this->buildDebtData($case,$payload,(int)$case['id']); $this->model->insert($d,true); $id=(int)$this->model->getInsertID(); $this->caseService->recalcTotals((int)$case['id']); $n=$this->show($id); $this->audit('legal.legal_case_debt.create.success',['entity_type'=>'legal_case_debt','entity_id'=>$id,'new_values'=>$n]); return $n; }); }
    public function delete(int $id): void { $old=$this->show($id); $caseId=(int)$old['legal_case_id']; $this->caseService->assertDebtMutable($caseId); $this->runDebtTransaction($caseId,function() use($id,$old,$caseId): void { $this->model->delete($id); $this->caseService->recalcTotals($caseId); $this->audit('legal.legal_case_debt.delete.success',['entity_type'=>'legal_case_debt','entity_id'=>$id,'old_values'=>$old]); }); }
    public function show(int $id): array { $r=Database::connect()->table('legal_case_debts')->where('id',$id)->get(1)->getRowArray(); if(!is_array($r)||($r['deleted_at']??null)!==null){throw new NotFoundApiException('Legal case debt bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0&&(int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} return $r; }
    /** @param array<string,mixed> $case @param array<string,mixed> $payload @return array<string,mixed> */ private function buildDebtData(array $case,array $payload,int $caseId): array { $dueId=(int)$payload['due_item_id']; $ctx=(int)(service('request')->company_id??0); $db=Database::connect(); $due=$db->table('due_items')->where('id',$dueId)->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($due)){throw new NotFoundApiException('Due item bulunamadi');} if((int)$due['company_id']!==$ctx){throw new ConflictApiException('due_item legal_case tenant ile uyumsuz');} if((int)$due['site_id']!==(int)$case['site_id']){throw new ConflictApiException('due_item.site legal_case.site ile uyumsuz');} if(($case['unit_id']??null)!==null && (int)$due['unit_id']!==(int)$case['unit_id']){throw new ConflictApiException('due_item.unit legal_case.unit ile uyumsuz');} if(($case['unit_id']??null)===null){ Database::connect()->table('legal_cases')->where('id',$caseId)->update(['unit_id'=>(int)$due['unit_id']]); } $dup=$this->model->builder()->select('id')->where('legal_case_id',$caseId)->where('due_item_id',$dueId)->where('deleted_at',null)->get(1)->getRowArray(); if($dup!==null){throw new ConflictApiException('Ayni case + due_item duplicate olamaz');} $principal=round((float)($due['remaining_amount']??$due['amount']??0),2); $interest=round((float)($payload['interest_amount']??0),2); $total=round($principal+$interest,2); return ['legal_case_id'=>$caseId,'due_item_id'=>$dueId,'principal_amount'=>$principal,'interest_amount'=>$interest,'total_amount'=>$total,'status'=>'active']; }
    private function runDebtTransaction(int $caseId,callable $callback): mixed { $db=Database::connect(); $ctx=(int)(service('request')->company_id??0); $db->transBegin(); try{ $case=$db->query("SELECT id,status FROM legal_cases WHERE id = ? AND company_id = ? AND deleted_at IS NULL FOR UPDATE",[$caseId,$ctx])->getRowArray(); if(!is_array($case)){throw new NotFoundApiException('Legal case bulunamadi');} if(in_array((string)$case['status'],['paid','closed','cancelled'],true)){throw new ConflictApiException('paid/cancelled/closed case debt degisikligine kapali');} $db->query("SELECT id FROM legal_case_debts WHERE company_id = ? AND legal_case_id = ? AND deleted_at IS NULL FOR UPDATE",[$ctx,$caseId])->getResultArray(); $result=$callback(); if($db->transStatus()===false){throw new ConflictApiException('Legal case debt islemi tamamlanamadi');} $db->transCommit(); return $result; }catch(\Throwable $e){$db->transRollback(); if($e instanceof ConflictApiException||$e instanceof NotFoundApiException||$e instanceof TenantAccessDeniedException){throw $e;} throw new ConflictApiException('Debt transaction tamamlanamadi');} }
}
