<?php
namespace App\Services\Operation;
use App\Core\BaseService;
use App\Exceptions\ConflictApiException;
use App\Exceptions\NotFoundApiException;
use App\Exceptions\TenantAccessDeniedException;
use App\Libraries\ListQuery;
use App\Models\MeetingAgendaItemModel;
use Config\Database;
use Throwable;
class MeetingAgendaService extends BaseService
{
    public function __construct(private readonly MeetingAgendaItemModel $model = new MeetingAgendaItemModel(), private readonly MeetingService $meetingService = new MeetingService()) { parent::__construct(); }
    public function listByMeeting(int $meetingId,array $query=[]): array { $this->meetingService->show($meetingId); $q=ListQuery::normalize($query,['sortable'=>['id','item_no','created_at'],'filterable'=>[]]); $b=$this->model->builder()->select('*')->where('meeting_id',$meetingId)->where('deleted_at',null); $t=(int)$b->countAllResults(false); $i=$b->orderBy($q['sort'],$q['direction'])->limit($q['per_page'],($q['page']-1)*$q['per_page'])->get()->getResultArray(); return ListQuery::envelope($q['page'],$q['per_page'],$t,$i); }
    public function create(int $meetingId,array $payload): array { $this->meetingService->assertNotLocked($meetingId); $id=$this->runAgendaTransaction($meetingId,null,function() use($meetingId,$payload): int { $itemNo=array_key_exists('item_no',$payload)&&$payload['item_no']!==null&&$payload['item_no']!==''?(int)$payload['item_no']:$this->nextItemNo($meetingId,true); $d=['meeting_id'=>$meetingId,'item_no'=>$itemNo,'title'=>trim((string)$payload['title']),'description'=>($payload['description']??'')===''?null:(string)$payload['description']]; $this->assertUnique($meetingId,$itemNo,null,true); $this->model->insert($d,true); return (int)$this->model->getInsertID(); }); $n=$this->show($id); $this->audit('governance.meeting_agenda.create.success',['entity_type'=>'meeting_agenda_item','entity_id'=>$id,'new_values'=>$n]); return $n; }
    public function update(int $id,array $payload): array { $old=$this->show($id); $this->meetingService->assertNotLocked((int)$old['meeting_id']); $meetingId=(int)$old['meeting_id']; $this->runAgendaTransaction($meetingId,$id,function() use($id,$meetingId,$old,$payload): void { $itemNo=array_key_exists('item_no',$payload)&&$payload['item_no']!==null&&$payload['item_no']!==''?(int)$payload['item_no']:(int)$old['item_no']; $this->assertUnique($meetingId,$itemNo,$id,true); $d=['item_no'=>$itemNo,'title'=>trim((string)($payload['title']??$old['title'])),'description'=>array_key_exists('description',$payload)?(($payload['description']??'')===''?null:(string)$payload['description']):($old['description']??null)]; $this->model->update($id,$d); }); $n=$this->show($id); $this->audit('governance.meeting_agenda.update.success',['entity_type'=>'meeting_agenda_item','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function delete(int $id): void { $old=$this->show($id); $this->meetingService->assertNotLocked((int)$old['meeting_id']); $this->model->delete($id); $this->audit('governance.meeting_agenda.delete.success',['entity_type'=>'meeting_agenda_item','entity_id'=>$id,'old_values'=>$old]); }
    public function show(int $id): array { $r=Database::connect()->table('meeting_agenda_items')->where('id',$id)->get(1)->getRowArray(); if(!is_array($r)||($r['deleted_at']??null)!==null){throw new NotFoundApiException('Meeting agenda item bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0&&(int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} return $r; }
    private function nextItemNo(int $meetingId,bool $forUpdate=false): int { $ctx=(int)(service('request')->company_id??0); $sql="SELECT COALESCE(MAX(item_no),0) AS m FROM meeting_agenda_items WHERE company_id = ? AND meeting_id = ? AND deleted_at IS NULL"; if($forUpdate){$sql.=" FOR UPDATE";} $m=(int)(Database::connect()->query($sql,[$ctx,$meetingId])->getRowArray()['m']??0); return $m+1; }
    private function assertUnique(int $meetingId,int $itemNo,?int $exceptId,bool $forUpdate=false): void { $ctx=(int)(service('request')->company_id??0); $sql="SELECT id FROM meeting_agenda_items WHERE company_id = ? AND meeting_id = ? AND item_no = ? AND deleted_at IS NULL"; $params=[$ctx,$meetingId,$itemNo]; if($exceptId!==null){$sql.=" AND id != ?"; $params[]=$exceptId;} if($forUpdate){$sql.=" FOR UPDATE";} if(Database::connect()->query($sql,$params)->getRowArray()!==null){throw new ConflictApiException('Agenda item_no meeting icinde unique olmali');} }
    private function runAgendaTransaction(int $meetingId,?int $excludeItemId,callable $callback): mixed { $db=Database::connect(); $ctx=(int)(service('request')->company_id??0); $db->transBegin(); try { $meeting=$db->query("SELECT id,status FROM meetings WHERE id = ? AND company_id = ? AND deleted_at IS NULL FOR UPDATE",[$meetingId,$ctx])->getRowArray(); if(!is_array($meeting)){throw new NotFoundApiException('Meeting bulunamadi');} if((string)($meeting['status']??'')==='locked'){throw new ConflictApiException('locked meeting uzerinde degisiklik yapilamaz');} $sql="SELECT id FROM meeting_agenda_items WHERE company_id = ? AND meeting_id = ? AND deleted_at IS NULL"; $params=[$ctx,$meetingId]; if($excludeItemId!==null){$sql.=" AND id != ?"; $params[]=$excludeItemId;} $sql.=" FOR UPDATE"; $db->query($sql,$params)->getResultArray(); $result=$callback(); if($db->transStatus()===false){throw new ConflictApiException('Meeting agenda islemi tamamlanamadi');} $db->transCommit(); return $result; } catch (Throwable $e) { $db->transRollback(); if($e instanceof ConflictApiException || $e instanceof NotFoundApiException || $e instanceof TenantAccessDeniedException){throw $e;} throw new ConflictApiException('Meeting agenda race kontrolu sirasinda islem tamamlanamadi'); } }
}
