<?php
namespace App\Services\Operation;
use App\Core\BaseService;
use App\Exceptions\ConflictApiException;
use App\Exceptions\NotFoundApiException;
use App\Exceptions\TenantAccessDeniedException;
use App\Libraries\ListQuery;
use App\Models\MeetingModel;
use Config\Database;
use Throwable;
class MeetingService extends BaseService
{
    public function __construct(private readonly MeetingModel $model = new MeetingModel()) { parent::__construct(); }
    public function list(array $query): array { $q=ListQuery::normalize($query,['sortable'=>['id','meeting_no','meeting_type','meeting_date','status','created_at'],'filterable'=>['site_id','meeting_type','status']]); $b=$this->model->builder()->select('*')->where('deleted_at',null); foreach($q['filters'] as $f=>$v){$b->where($f,$v);} if($q['search']!==''){$b->groupStart()->like('meeting_no',$q['search'])->orLike('title',$q['search'])->groupEnd();} $t=(int)$b->countAllResults(false); $i=$b->orderBy($q['sort'],$q['direction'])->limit($q['per_page'],($q['page']-1)*$q['per_page'])->get()->getResultArray(); return ListQuery::envelope($q['page'],$q['per_page'],$t,$i); }
    public function show(int $id): array { $r=Database::connect()->table('meetings')->where('id',$id)->get(1)->getRowArray(); if(!is_array($r)||($r['deleted_at']??null)!==null){throw new NotFoundApiException('Meeting bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0&&(int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} return $r; }
    public function create(array $payload): array { $d=$this->normalize($payload); $this->assertSiteTenant((int)$d['site_id']); $d['meeting_no']=$this->generateMeetingNo(); $this->model->insert($d,true); $id=(int)$this->model->getInsertID(); $n=$this->show($id); $this->audit('governance.meeting.create.success',['entity_type'=>'meeting','entity_id'=>$id,'new_values'=>$n]); return $n; }
    public function update(int $id,array $payload): array { $old=$this->show($id); if(in_array((string)$old['status'],['completed','cancelled','locked'],true)){throw new ConflictApiException('completed/cancelled/locked meeting update edilemez');} $d=$this->normalize($payload,$old); $this->assertSiteTenant((int)$d['site_id']); $this->model->update($id,$d); $n=$this->show($id); $this->audit('governance.meeting.update.success',['entity_type'=>'meeting','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function publish(int $id): array { $old=$this->show($id); if((string)$old['status']!=='draft'){throw new ConflictApiException('publish sadece draft icin calisir');} $this->model->update($id,['status'=>'published','published_at'=>date('Y-m-d H:i:s')]); $n=$this->show($id); $this->audit('governance.meeting.publish.success',['entity_type'=>'meeting','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function complete(int $id): array { $old=$this->show($id); if((string)$old['status']!=='published'){throw new ConflictApiException('complete sadece published icin calisir');} $this->model->update($id,['status'=>'completed','completed_at'=>date('Y-m-d H:i:s')]); $n=$this->show($id); $this->audit('governance.meeting.complete.success',['entity_type'=>'meeting','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function cancel(int $id): array { $old=$this->show($id); if(!in_array((string)$old['status'],['draft','published'],true)){throw new ConflictApiException('cancel sadece draft/published icin calisir');} $this->model->update($id,['status'=>'cancelled']); $n=$this->show($id); $this->audit('governance.meeting.cancel.success',['entity_type'=>'meeting','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function lock(int $id): array { $old=$this->show($id); if((string)$old['status']!=='completed'){throw new ConflictApiException('lock sadece completed icin calisir');} $this->model->update($id,['status'=>'locked','locked_at'=>date('Y-m-d H:i:s')]); $n=$this->show($id); $this->audit('governance.meeting.lock.success',['entity_type'=>'meeting','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function assertNotLocked(int $id): array { $m=$this->show($id); if((string)$m['status']==='locked'){throw new ConflictApiException('locked meeting uzerinde degisiklik yapilamaz');} return $m; }
    /** @return array<string,mixed> */ private function normalize(array $p,array $c=[]): array { return ['site_id'=>(int)($p['site_id']??$c['site_id']??0),'meeting_type'=>(string)($p['meeting_type']??$c['meeting_type']??''),'title'=>trim((string)($p['title']??$c['title']??'')),'description'=>array_key_exists('description',$p)?(($p['description']??'')===''?null:trim((string)$p['description'])):($c['description']??null),'meeting_date'=>(string)($p['meeting_date']??$c['meeting_date']??''),'location'=>array_key_exists('location',$p)?(($p['location']??'')===''?null:trim((string)$p['location'])):($c['location']??null),'status'=>(string)($c['status']??'draft')]; }
    private function assertSiteTenant(int $siteId): void { $s=Database::connect()->table('sites')->where('id',$siteId)->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($s)){throw new NotFoundApiException('Site bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0&&(int)$s['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} }
    private function generateMeetingNo(): string { for($i=0;$i<5;$i++){ $no='MTG-'.date('YmdHis').'-'.strtoupper(substr(bin2hex(random_bytes(2)),0,4)); try{$this->assertMeetingNoUnique($no); return $no;}catch(Throwable){}} throw new ConflictApiException('meeting_no uretilemedi'); }
    private function assertMeetingNoUnique(string $meetingNo): void { $ctx=(int)(service('request')->company_id??0); $r=$this->model->builder()->select('id')->where('company_id',$ctx)->where('meeting_no',$meetingNo)->where('deleted_at',null)->get(1)->getRowArray(); if($r!==null){throw new ConflictApiException('meeting_no unique olmali');} }
}
