<?php
namespace App\Services\Operation;
use App\Core\BaseService;
use App\Exceptions\ConflictApiException;
use App\Exceptions\NotFoundApiException;
use App\Exceptions\TenantAccessDeniedException;
use App\Libraries\ListQuery;
use App\Models\MeetingAttendeeModel;
use Config\Database;
class MeetingAttendeeService extends BaseService
{
    public function __construct(private readonly MeetingAttendeeModel $model = new MeetingAttendeeModel(), private readonly MeetingService $meetingService = new MeetingService()) { parent::__construct(); }
    public function listByMeeting(int $meetingId,array $query=[]): array { $this->meetingService->show($meetingId); $q=ListQuery::normalize($query,['sortable'=>['id','attendance_type','status','created_at'],'filterable'=>['attendance_type','status']]); $b=$this->model->builder()->select('*')->where('meeting_id',$meetingId)->where('deleted_at',null); foreach($q['filters'] as $f=>$v){$b->where($f,$v);} $t=(int)$b->countAllResults(false); $i=$b->orderBy($q['sort'],$q['direction'])->limit($q['per_page'],($q['page']-1)*$q['per_page'])->get()->getResultArray(); return ListQuery::envelope($q['page'],$q['per_page'],$t,$i); }
    public function create(int $meetingId,array $payload): array { $meeting=$this->meetingService->assertNotLocked($meetingId); $d=$this->normalize($payload); $d['meeting_id']=$meetingId; $this->assertReferences((int)$meeting['site_id'],$d); $this->assertDuplicate($meetingId,$d,null); $this->model->insert($d,true); $id=(int)$this->model->getInsertID(); $n=$this->show($id); $this->audit('governance.meeting_attendee.create.success',['entity_type'=>'meeting_attendee','entity_id'=>$id,'new_values'=>$n]); return $n; }
    public function update(int $id,array $payload): array { $old=$this->show($id); $meeting=$this->meetingService->assertNotLocked((int)$old['meeting_id']); $d=$this->normalize($payload,$old); $this->assertReferences((int)$meeting['site_id'],$d); $this->assertDuplicate((int)$old['meeting_id'],$d,$id); $this->model->update($id,$d); $n=$this->show($id); $this->audit('governance.meeting_attendee.update.success',['entity_type'=>'meeting_attendee','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function sign(int $id): array { $old=$this->show($id); $this->meetingService->assertNotLocked((int)$old['meeting_id']); if(in_array((string)$old['status'],['cancelled','attended'],true)){throw new ConflictApiException('cancelled/attended attendee sign edilemez');} if(!in_array((string)$old['status'],['invited','absent'],true)){throw new ConflictApiException('sign sadece invited/absent icin calisir');} $this->model->update($id,['signed_at'=>date('Y-m-d H:i:s'),'status'=>'attended']); $n=$this->show($id); $this->audit('governance.meeting_attendee.sign.success',['entity_type'=>'meeting_attendee','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function delete(int $id): void { $old=$this->show($id); $this->meetingService->assertNotLocked((int)$old['meeting_id']); $this->model->delete($id); $this->audit('governance.meeting_attendee.delete.success',['entity_type'=>'meeting_attendee','entity_id'=>$id,'old_values'=>$old]); }
    public function show(int $id): array { $r=Database::connect()->table('meeting_attendees')->where('id',$id)->get(1)->getRowArray(); if(!is_array($r)||($r['deleted_at']??null)!==null){throw new NotFoundApiException('Meeting attendee bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0&&(int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} return $r; }
    /** @return array<string,mixed> */ private function normalize(array $p,array $c=[]): array { return ['resident_profile_id'=>array_key_exists('resident_profile_id',$p)?($p['resident_profile_id']===''||$p['resident_profile_id']===null?null:(int)$p['resident_profile_id']):($c['resident_profile_id']??null),'unit_id'=>array_key_exists('unit_id',$p)?($p['unit_id']===''||$p['unit_id']===null?null:(int)$p['unit_id']):($c['unit_id']??null),'attendance_type'=>(string)($p['attendance_type']??$c['attendance_type']??''),'proxy_for_resident_id'=>array_key_exists('proxy_for_resident_id',$p)?($p['proxy_for_resident_id']===''||$p['proxy_for_resident_id']===null?null:(int)$p['proxy_for_resident_id']):($c['proxy_for_resident_id']??null),'land_share'=>array_key_exists('land_share',$p)?($p['land_share']===''||$p['land_share']===null?null:(float)$p['land_share']):($c['land_share']??null),'vote_weight'=>array_key_exists('vote_weight',$p)?($p['vote_weight']===''||$p['vote_weight']===null?null:(float)$p['vote_weight']):($c['vote_weight']??null),'status'=>(string)($p['status']??$c['status']??'invited')]; }
    /** @param array<string,mixed> $d */ private function assertReferences(int $meetingSiteId,array $d): void { $db=Database::connect(); $ctx=(int)(service('request')->company_id??0); if($d['unit_id']!==null){$u=$db->table('units')->where('id',(int)$d['unit_id'])->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($u)){throw new NotFoundApiException('Unit bulunamadi');} if((int)$u['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} if((int)$u['site_id']!==$meetingSiteId){throw new ConflictApiException('unit meeting.site ile uyumsuz');}} if($d['resident_profile_id']!==null){$r=$db->table('resident_profiles')->where('id',(int)$d['resident_profile_id'])->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($r)){throw new NotFoundApiException('Resident bulunamadi');} if((int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} if($d['unit_id']!==null){$occ=$db->table('unit_occupancies')->where('company_id',$ctx)->where('unit_id',(int)$d['unit_id'])->where('resident_profile_id',(int)$d['resident_profile_id'])->where('status','active')->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($occ)){throw new ConflictApiException('resident unit ile aktif occupancy iliskisinde olmali');}} } if($d['proxy_for_resident_id']!==null){$p=$db->table('resident_profiles')->where('id',(int)$d['proxy_for_resident_id'])->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($p)){throw new NotFoundApiException('Proxy resident bulunamadi');} if((int)$p['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} if($d['resident_profile_id']!==null && (int)$d['resident_profile_id']===(int)$d['proxy_for_resident_id']){throw new ConflictApiException('proxy_for_resident resident ile ayni olamaz');}} }
    /** @param array<string,mixed> $d */ private function assertDuplicate(int $meetingId,array $d,?int $exceptId): void { $b=$this->model->builder()->select('id')->where('meeting_id',$meetingId)->where('attendance_type',(string)$d['attendance_type'])->where('deleted_at',null)->whereIn('status',['invited','attended','absent']); if($d['resident_profile_id']===null){$b->where('resident_profile_id',null);} else{$b->where('resident_profile_id',(int)$d['resident_profile_id']);} if($d['unit_id']===null){$b->where('unit_id',null);} else{$b->where('unit_id',(int)$d['unit_id']);} if($exceptId!==null){$b->where('id !=',$exceptId);} if($b->get(1)->getRowArray()!==null){throw new ConflictApiException('duplicate attendee engellendi');} }
}
