<?php
namespace App\Services\Operation;
use App\Core\BaseService; use App\Exceptions\ConflictApiException; use App\Exceptions\NotFoundApiException; use App\Exceptions\TenantAccessDeniedException; use App\Libraries\ListQuery; use App\Models\SecurityIncidentModel; use Config\Database;
class SecurityIncidentService extends BaseService
{
    public function __construct(private readonly SecurityIncidentModel $model = new SecurityIncidentModel()){ parent::__construct(); }
    public function list(array $query): array { $q=ListQuery::normalize($query,['sortable'=>['id','severity','status','created_at'],'filterable'=>['site_id','unit_id','severity','status']]); $b=$this->model->builder()->select('*')->where('deleted_at',null); foreach($q['filters'] as $f=>$v){$b->where($f,$v);} if($q['search']!==''){$b->groupStart()->like('title',$q['search'])->orLike('description',$q['search'])->groupEnd();} $t=(int)$b->countAllResults(false); $i=$b->orderBy($q['sort'],$q['direction'])->limit($q['per_page'],($q['page']-1)*$q['per_page'])->get()->getResultArray(); return ListQuery::envelope($q['page'],$q['per_page'],$t,$i);}
    public function show(int $id): array { $this->assertAccessible($id); $r=$this->model->tenantFind($id); if(!is_array($r)){throw new NotFoundApiException('Incident bulunamadi');} return $r; }
    public function create(array $p): array { $this->assertSiteUnit((int)$p['site_id'],isset($p['unit_id'])?(int)$p['unit_id']:null); $this->model->insert(['site_id'=>(int)$p['site_id'],'unit_id'=>$p['unit_id']??null,'title'=>(string)$p['title'],'description'=>$p['description']??null,'severity'=>(string)($p['severity']??'normal'),'status'=>'open','reported_by'=>$p['reported_by']??null],true); $id=(int)$this->model->getInsertID(); $c=$this->show($id); $this->audit('security.security_incident.create.success',['entity_type'=>'security_incident','entity_id'=>$id,'new_values'=>$c]); return $c; }
    public function update(int $id,array $p): array { $old=$this->show($id); if(in_array((string)$old['status'],['closed','cancelled'],true)){throw new ConflictApiException('closed/cancelled incident guncellenemez');} $d=[]; foreach(['title','description','severity','reported_by'] as $f){ if(array_key_exists($f,$p)){$d[$f]=$p[$f];}} if($d!==[]){$this->model->update($id,$d);} $n=$this->show($id); $this->audit('security.security_incident.update.success',['entity_type'=>'security_incident','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function resolve(int $id): array { $old=$this->show($id); if(!in_array((string)$old['status'],['open','investigating'],true)){throw new ConflictApiException('resolve sadece open/investigating icin calisir');} $this->model->update($id,['status'=>'resolved','resolved_at'=>date('Y-m-d H:i:s')]); $n=$this->show($id); $this->audit('security.security_incident.resolve.success',['entity_type'=>'security_incident','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function close(int $id): array { $old=$this->show($id); if((string)$old['status']!=='resolved'){throw new ConflictApiException('close sadece resolved icin calisir');} $this->model->update($id,['status'=>'closed','closed_at'=>date('Y-m-d H:i:s')]); $n=$this->show($id); $this->audit('security.security_incident.close.success',['entity_type'=>'security_incident','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function cancel(int $id): array { $old=$this->show($id); if(!in_array((string)$old['status'],['open','investigating','resolved'],true)){throw new ConflictApiException('cancel open/investigating/resolved icin calisir');} $this->model->update($id,['status'=>'cancelled']); $n=$this->show($id); $this->audit('security.security_incident.cancel.success',['entity_type'=>'security_incident','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    private function assertSiteUnit(int $siteId,?int $unitId): void { $db=Database::connect(); $ctx=(int)(service('request')->company_id??0); $s=$db->table('sites')->where('id',$siteId)->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($s)){throw new NotFoundApiException('Site bulunamadi');} if($ctx>0&&(int)$s['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} if($unitId!==null){$u=$db->table('units')->where('id',$unitId)->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($u)){throw new NotFoundApiException('Unit bulunamadi');} if((int)$u['site_id']!==$siteId){throw new ConflictApiException('unit/site uyumsuz');} if($ctx>0&&(int)$u['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');}} }
    private function assertAccessible(int $id): void { $r=Database::connect()->table('security_incidents')->where('id',$id)->get(1)->getRowArray(); if(!is_array($r)||($r['deleted_at']??null)!==null){throw new NotFoundApiException('Incident bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0&&(int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} }
}
