<?php
namespace App\Services\Operation;
use App\Core\BaseService;
use App\Exceptions\ConflictApiException;
use App\Exceptions\NotFoundApiException;
use App\Exceptions\TenantAccessDeniedException;
use App\Libraries\ListQuery;
use App\Models\StaffAssignmentModel;
use Config\Database;
class StaffAssignmentService extends BaseService
{
    public function __construct(private readonly StaffAssignmentModel $model = new StaffAssignmentModel(), private readonly StaffProfileService $profileService = new StaffProfileService()) { parent::__construct(); }
    public function list(array $query): array { $q=ListQuery::normalize($query,['sortable'=>['id','staff_profile_id','site_id','start_date','status','created_at'],'filterable'=>['staff_profile_id','site_id','block_id','status']]); $b=$this->model->builder()->select('*')->where('deleted_at',null); foreach($q['filters'] as $f=>$v){$b->where($f,$v);} $t=(int)$b->countAllResults(false); $i=$b->orderBy($q['sort'],$q['direction'])->limit($q['per_page'],($q['page']-1)*$q['per_page'])->get()->getResultArray(); return ListQuery::envelope($q['page'],$q['per_page'],$t,$i);}
    public function show(int $id): array { $r=Database::connect()->table('staff_assignments')->where('id',$id)->get(1)->getRowArray(); if(!is_array($r)||($r['deleted_at']??null)!==null){throw new NotFoundApiException('Staff assignment bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0 && (int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} return $r; }
    public function create(array $payload): array { $d=$this->normalize($payload); $this->assertReferences($d); $this->assertDateRange($d['start_date'],$d['end_date']); $id=$this->runOverlapTransaction((int)$d['staff_profile_id'],(int)$d['site_id'],$d['block_id'],(string)$d['start_date'],$d['end_date'],null,function() use($d): int { $this->assertNoOverlap($d,null,true); $this->model->insert($d,true); return (int)$this->model->getInsertID(); }); $n=$this->show($id); $this->audit('operation.staff_assignment.create.success',['entity_type'=>'staff_assignment','entity_id'=>$id,'new_values'=>$n]); return $n; }
    public function update(int $id,array $payload): array { $old=$this->show($id); $d=$this->normalize($payload,$old); $this->assertReferences($d); $this->assertDateRange((string)$d['start_date'],$d['end_date']); $this->runOverlapTransaction((int)$d['staff_profile_id'],(int)$d['site_id'],$d['block_id'],(string)$d['start_date'],$d['end_date'],$id,function() use($id,$d): void { $this->assertNoOverlap($d,$id,true); $this->model->update($id,$d); }); $n=$this->show($id); $this->audit('operation.staff_assignment.update.success',['entity_type'=>'staff_assignment','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function delete(int $id): void { $old=$this->show($id); $this->model->delete($id); $this->audit('operation.staff_assignment.delete.success',['entity_type'=>'staff_assignment','entity_id'=>$id,'old_values'=>$old]); }
    /** @param array<string,mixed> $d */ private function assertReferences(array $d): void { $this->profileService->show((int)$d['staff_profile_id']); $db=Database::connect(); $ctx=(int)(service('request')->company_id??0); $s=$db->table('sites')->where('id',(int)$d['site_id'])->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($s)){throw new NotFoundApiException('Site bulunamadi');} if($ctx>0&&(int)$s['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} if($d['block_id']!==null){$b=$db->table('blocks')->where('id',(int)$d['block_id'])->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($b)){throw new NotFoundApiException('Block bulunamadi');} if($ctx>0&&(int)$b['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} if((int)$b['site_id']!==(int)$d['site_id']){throw new ConflictApiException('block.site_id assignment.site_id ile uyumsuz');}} }
    private function assertDateRange(string $start,?string $end): void { if($end!==null && $end!=='' && strtotime($end)<strtotime($start)){throw new ConflictApiException('end_date start_date ten kucuk olamaz');} }
    /** @param array<string,mixed> $d */ private function assertNoOverlap(array $d,?int $exceptId,bool $forUpdate=false): void { if((string)$d['status']!=='active'){return;} $db=Database::connect(); $ctx=(int)(service('request')->company_id??0); $sql="SELECT id,start_date,end_date FROM staff_assignments WHERE company_id = ? AND staff_profile_id = ? AND site_id = ? AND deleted_at IS NULL AND status = 'active'"; $params=[$ctx,(int)$d['staff_profile_id'],(int)$d['site_id']]; if($d['block_id']===null){$sql.=" AND block_id IS NULL";} else{$sql.=" AND block_id = ?"; $params[]=(int)$d['block_id'];} if($exceptId!==null){$sql.=" AND id != ?"; $params[]=$exceptId;} if($forUpdate){$sql.=" FOR UPDATE";} $rows=$db->query($sql,$params)->getResultArray(); foreach($rows as $cur){$s1=strtotime((string)$d['start_date']); $e1=$d['end_date']?strtotime((string)$d['end_date']):strtotime('9999-12-31'); $s2=strtotime((string)$cur['start_date']); $e2=($cur['end_date']??null)?strtotime((string)$cur['end_date']):strtotime('9999-12-31'); if($s1<=$e2 && $s2<=$e1){throw new ConflictApiException('aktif assignment overlap engellendi');}} }
    private function runOverlapTransaction(int $staffProfileId,int $siteId,?int $blockId,string $startDate,?string $endDate,?int $excludeId,callable $callback): mixed { $db=Database::connect(); $ctx=(int)(service('request')->company_id??0); $db->transBegin(); try{ $lockSql="SELECT id FROM staff_profiles WHERE id = ? AND company_id = ? AND deleted_at IS NULL FOR UPDATE"; $lock=$db->query($lockSql,[$staffProfileId,$ctx])->getRowArray(); if(!is_array($lock)){throw new NotFoundApiException('Staff profile bulunamadi');} $scopeSql="SELECT id FROM staff_assignments WHERE company_id = ? AND staff_profile_id = ? AND site_id = ? AND deleted_at IS NULL"; $scopeParams=[$ctx,$staffProfileId,$siteId]; if($blockId===null){$scopeSql.=" AND block_id IS NULL";} else{$scopeSql.=" AND block_id = ?"; $scopeParams[]=$blockId;} if($excludeId!==null){$scopeSql.=" AND id != ?"; $scopeParams[]=$excludeId;} $scopeSql.=" FOR UPDATE"; $db->query($scopeSql,$scopeParams)->getResultArray(); $this->assertNoOverlap(['staff_profile_id'=>$staffProfileId,'site_id'=>$siteId,'block_id'=>$blockId,'start_date'=>$startDate,'end_date'=>$endDate,'status'=>'active'],$excludeId,true); $result=$callback(); if($db->transStatus()===false){throw new ConflictApiException('Assignment kaydi sirasinda islem tamamlanamadi');} $db->transCommit(); return $result; }catch(\Throwable $e){$db->transRollback(); if($e instanceof ConflictApiException || $e instanceof NotFoundApiException || $e instanceof TenantAccessDeniedException){throw $e;} throw new ConflictApiException('Assignment overlap kontrolu sirasinda islem tamamlanamadi');} }
    /** @return array<string,mixed> */ private function normalize(array $p,array $c=[]): array { return ['staff_profile_id'=>(int)($p['staff_profile_id']??$c['staff_profile_id']??0),'site_id'=>(int)($p['site_id']??$c['site_id']??0),'block_id'=>array_key_exists('block_id',$p)?($p['block_id']===''||$p['block_id']===null?null:(int)$p['block_id']):($c['block_id']??null),'role_note'=>array_key_exists('role_note',$p)?(($p['role_note']??'')===''?null:trim((string)$p['role_note'])):($c['role_note']??null),'start_date'=>(string)($p['start_date']??$c['start_date']??''),'end_date'=>array_key_exists('end_date',$p)?(($p['end_date']??'')===''?null:(string)$p['end_date']):($c['end_date']??null),'status'=>(string)($p['status']??$c['status']??'active')]; }
}
