<?php
namespace App\Services\Operation;
use App\Core\BaseService;
use App\Exceptions\ConflictApiException;
use App\Exceptions\NotFoundApiException;
use App\Exceptions\TenantAccessDeniedException;
use App\Libraries\ListQuery;
use App\Models\StaffShiftModel;
use Config\Database;
class StaffShiftService extends BaseService
{
    public function __construct(private readonly StaffShiftModel $model = new StaffShiftModel(), private readonly StaffProfileService $profileService = new StaffProfileService()) { parent::__construct(); }
    public function list(array $query): array { $q=ListQuery::normalize($query,['sortable'=>['id','shift_date','start_at','end_at','status','created_at'],'filterable'=>['staff_profile_id','site_id','shift_date','status']]); $b=$this->model->builder()->select('*')->where('deleted_at',null); foreach($q['filters'] as $f=>$v){$b->where($f,$v);} $t=(int)$b->countAllResults(false); $i=$b->orderBy($q['sort'],$q['direction'])->limit($q['per_page'],($q['page']-1)*$q['per_page'])->get()->getResultArray(); return ListQuery::envelope($q['page'],$q['per_page'],$t,$i);}
    public function show(int $id): array { $r=Database::connect()->table('staff_shifts')->where('id',$id)->get(1)->getRowArray(); if(!is_array($r)||($r['deleted_at']??null)!==null){throw new NotFoundApiException('Staff shift bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0 && (int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} return $r; }
    public function create(array $payload): array { $d=$this->normalize($payload); $this->assertReferences($d); $this->assertTimeline((string)$d['shift_date'],(string)$d['start_at'],(string)$d['end_at']); $id=$this->runOverlapTransaction((int)$d['staff_profile_id'],(string)$d['start_at'],(string)$d['end_at'],null,function() use($d): int { $this->assertNoOverlap($d,null,true); $this->model->insert($d,true); return (int)$this->model->getInsertID(); }); $n=$this->show($id); $this->audit('operation.staff_shift.create.success',['entity_type'=>'staff_shift','entity_id'=>$id,'new_values'=>$n]); return $n; }
    public function update(int $id,array $payload): array { $old=$this->show($id); if(in_array((string)$old['status'],['completed','cancelled'],true)){throw new ConflictApiException('completed/cancelled shift update edilemez');} $d=$this->normalize($payload,$old); $this->assertReferences($d); $this->assertTimeline((string)$d['shift_date'],(string)$d['start_at'],(string)$d['end_at']); $this->runOverlapTransaction((int)$d['staff_profile_id'],(string)$d['start_at'],(string)$d['end_at'],$id,function() use($id,$d): void { $this->assertNoOverlap($d,$id,true); $this->model->update($id,$d); }); $n=$this->show($id); $this->audit('operation.staff_shift.update.success',['entity_type'=>'staff_shift','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function start(int $id): array { $old=$this->show($id); if((string)$old['status']!=='planned'){throw new ConflictApiException('planned shift start edilebilir');} $this->model->update($id,['status'=>'started']); $n=$this->show($id); $this->audit('operation.staff_shift.start.success',['entity_type'=>'staff_shift','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function complete(int $id): array { $old=$this->show($id); if((string)$old['status']!=='started'){throw new ConflictApiException('started shift complete edilebilir');} $this->model->update($id,['status'=>'completed']); $n=$this->show($id); $this->audit('operation.staff_shift.complete.success',['entity_type'=>'staff_shift','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function cancel(int $id): array { $old=$this->show($id); if(!in_array((string)$old['status'],['planned','started'],true)){throw new ConflictApiException('planned/started shift cancel edilebilir');} $this->model->update($id,['status'=>'cancelled']); $n=$this->show($id); $this->audit('operation.staff_shift.cancel.success',['entity_type'=>'staff_shift','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    /** @param array<string,mixed> $d */ private function assertReferences(array $d): void { $this->profileService->show((int)$d['staff_profile_id']); $s=Database::connect()->table('sites')->where('id',(int)$d['site_id'])->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($s)){throw new NotFoundApiException('Site bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0 && (int)$s['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} }
    private function assertTimeline(string $shiftDate,string $startAt,string $endAt): void { if(strtotime($startAt)>=strtotime($endAt)){throw new ConflictApiException('shift start_at end_at ten kucuk olmali');} if(date('Y-m-d',strtotime($startAt))!==$shiftDate){throw new ConflictApiException('shift_date start_at tarihiyle uyumlu olmali');} }
    /** @param array<string,mixed> $d */ private function assertNoOverlap(array $d,?int $exceptId,bool $forUpdate=false): void { if(!in_array((string)$d['status'],['planned','started'],true)){return;} $db=Database::connect(); $ctx=(int)(service('request')->company_id??0); $sql="SELECT id,start_at,end_at FROM staff_shifts WHERE company_id = ? AND staff_profile_id = ? AND deleted_at IS NULL AND status IN ('planned','started')"; $params=[$ctx,(int)$d['staff_profile_id']]; if($exceptId!==null){$sql.=" AND id != ?"; $params[]=$exceptId;} if($forUpdate){$sql.=" FOR UPDATE";} foreach($db->query($sql,$params)->getResultArray() as $r){ if(strtotime((string)$d['start_at'])<strtotime((string)$r['end_at']) && strtotime((string)$r['start_at'])<strtotime((string)$d['end_at'])){throw new ConflictApiException('shift overlap engellendi');}} }
    private function runOverlapTransaction(int $staffProfileId,string $startAt,string $endAt,?int $excludeId,callable $callback): mixed { $db=Database::connect(); $ctx=(int)(service('request')->company_id??0); $db->transBegin(); try{ $staff=$db->query("SELECT id FROM staff_profiles WHERE id = ? AND company_id = ? AND deleted_at IS NULL FOR UPDATE",[$staffProfileId,$ctx])->getRowArray(); if(!is_array($staff)){throw new NotFoundApiException('Staff profile bulunamadi');} $sql="SELECT id FROM staff_shifts WHERE company_id = ? AND staff_profile_id = ? AND deleted_at IS NULL AND status IN ('planned','started')"; $params=[$ctx,$staffProfileId]; if($excludeId!==null){$sql.=" AND id != ?"; $params[]=$excludeId;} $sql.=" FOR UPDATE"; $db->query($sql,$params)->getResultArray(); $this->assertNoOverlap(['staff_profile_id'=>$staffProfileId,'start_at'=>$startAt,'end_at'=>$endAt,'status'=>'planned'],$excludeId,true); $result=$callback(); if($db->transStatus()===false){throw new ConflictApiException('Shift kaydi sirasinda islem tamamlanamadi');} $db->transCommit(); return $result; }catch(\Throwable $e){$db->transRollback(); if($e instanceof ConflictApiException || $e instanceof NotFoundApiException || $e instanceof TenantAccessDeniedException){throw $e;} throw new ConflictApiException('Shift overlap kontrolu sirasinda islem tamamlanamadi');} }
    /** @return array<string,mixed> */ private function normalize(array $p,array $c=[]): array { return ['staff_profile_id'=>(int)($p['staff_profile_id']??$c['staff_profile_id']??0),'site_id'=>(int)($p['site_id']??$c['site_id']??0),'shift_date'=>(string)($p['shift_date']??$c['shift_date']??''),'start_at'=>(string)($p['start_at']??$c['start_at']??''),'end_at'=>(string)($p['end_at']??$c['end_at']??''),'status'=>(string)($p['status']??$c['status']??'planned'),'notes'=>array_key_exists('notes',$p)?(($p['notes']??'')===''?null:trim((string)$p['notes'])):($c['notes']??null)]; }
}
