<?php
namespace App\Services\Operation;
use App\Core\BaseService;
use App\Exceptions\ConflictApiException;
use App\Exceptions\NotFoundApiException;
use App\Exceptions\TenantAccessDeniedException;
use App\Libraries\ListQuery;
use App\Models\StaffTaskModel;
use Config\Database;
class StaffTaskService extends BaseService
{
    public function __construct(private readonly StaffTaskModel $model = new StaffTaskModel(), private readonly StaffProfileService $profileService = new StaffProfileService()) { parent::__construct(); }
    public function list(array $query): array { $q=ListQuery::normalize($query,['sortable'=>['id','priority','status','due_at','created_at'],'filterable'=>['staff_profile_id','site_id','work_order_id','priority','status']]); $b=$this->model->builder()->select('*')->where('deleted_at',null); foreach($q['filters'] as $f=>$v){$b->where($f,$v);} if($q['search']!==''){$b->groupStart()->like('title',$q['search'])->orLike('description',$q['search'])->groupEnd();} $t=(int)$b->countAllResults(false); $i=$b->orderBy($q['sort'],$q['direction'])->limit($q['per_page'],($q['page']-1)*$q['per_page'])->get()->getResultArray(); return ListQuery::envelope($q['page'],$q['per_page'],$t,$i);}
    public function show(int $id): array { $r=Database::connect()->table('staff_tasks')->where('id',$id)->get(1)->getRowArray(); if(!is_array($r)||($r['deleted_at']??null)!==null){throw new NotFoundApiException('Staff task bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0 && (int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} return $r; }
    public function create(array $payload): array { $d=$this->normalize($payload); $this->assertReferences($d); $this->assertAssignedRule($d); $this->model->insert($d,true); $id=(int)$this->model->getInsertID(); $n=$this->show($id); $this->audit('operation.staff_task.create.success',['entity_type'=>'staff_task','entity_id'=>$id,'new_values'=>$n]); return $n; }
    public function update(int $id,array $payload): array { $old=$this->show($id); if(in_array((string)$old['status'],['completed','cancelled'],true)){throw new ConflictApiException('completed/cancelled task update edilemez');} $d=$this->normalize($payload,$old); $this->assertReferences($d); $this->assertAssignedRule($d); $this->model->update($id,$d); $n=$this->show($id); $this->audit('operation.staff_task.update.success',['entity_type'=>'staff_task','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function assign(int $id,int $staffProfileId): array { $old=$this->show($id); if((string)$old['status']!=='open'){throw new ConflictApiException('open task assign edilebilir');} $this->profileService->assertActive($staffProfileId); $this->model->update($id,['staff_profile_id'=>$staffProfileId,'status'=>'assigned']); $n=$this->show($id); $this->audit('operation.staff_task.assign.success',['entity_type'=>'staff_task','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function start(int $id): array { $old=$this->show($id); if((string)$old['status']!=='assigned'){throw new ConflictApiException('assigned task start edilebilir');} if(($old['staff_profile_id']??null)===null){throw new ConflictApiException('assigned task icin staff_profile_id zorunlu');} $this->model->update($id,['status'=>'in_progress']); $n=$this->show($id); $this->audit('operation.staff_task.start.success',['entity_type'=>'staff_task','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function complete(int $id,array $payload=[]): array { $old=$this->show($id); if((string)$old['status']!=='in_progress'){throw new ConflictApiException('in_progress task complete edilebilir');} $this->model->update($id,['status'=>'completed','completed_at'=>date('Y-m-d H:i:s'),'proof_note'=>array_key_exists('proof_note',$payload)?(($payload['proof_note']??'')===''?null:(string)$payload['proof_note']):($old['proof_note']??null),'proof_file_path'=>array_key_exists('proof_file_path',$payload)?(($payload['proof_file_path']??'')===''?null:(string)$payload['proof_file_path']):($old['proof_file_path']??null)]); $n=$this->show($id); $this->audit('operation.staff_task.complete.success',['entity_type'=>'staff_task','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function cancel(int $id): array { $old=$this->show($id); if(!in_array((string)$old['status'],['open','assigned','in_progress'],true)){throw new ConflictApiException('open/assigned/in_progress task cancel edilebilir');} $this->model->update($id,['status'=>'cancelled']); $n=$this->show($id); $this->audit('operation.staff_task.cancel.success',['entity_type'=>'staff_task','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    /** @param array<string,mixed> $d */ private function assertReferences(array $d): void { $db=Database::connect(); $ctx=(int)(service('request')->company_id??0); $s=$db->table('sites')->where('id',(int)$d['site_id'])->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($s)){throw new NotFoundApiException('Site bulunamadi');} if($ctx>0 && (int)$s['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} if($d['staff_profile_id']!==null){$this->profileService->assertActive((int)$d['staff_profile_id']);} if($d['work_order_id']!==null){$w=$db->table('work_orders')->where('id',(int)$d['work_order_id'])->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($w)){throw new NotFoundApiException('Work order bulunamadi');} if($ctx>0 && (int)$w['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');}} }
    /** @param array<string,mixed> $d */ private function assertAssignedRule(array $d): void { if((string)$d['status']==='assigned' && $d['staff_profile_id']===null){throw new ConflictApiException('assigned task icin staff_profile_id zorunlu');} }
    /** @return array<string,mixed> */ private function normalize(array $p,array $c=[]): array { return ['staff_profile_id'=>array_key_exists('staff_profile_id',$p)?($p['staff_profile_id']===''||$p['staff_profile_id']===null?null:(int)$p['staff_profile_id']):($c['staff_profile_id']??null),'site_id'=>(int)($p['site_id']??$c['site_id']??0),'work_order_id'=>array_key_exists('work_order_id',$p)?($p['work_order_id']===''||$p['work_order_id']===null?null:(int)$p['work_order_id']):($c['work_order_id']??null),'title'=>trim((string)($p['title']??$c['title']??'')),'description'=>array_key_exists('description',$p)?(($p['description']??'')===''?null:trim((string)$p['description'])):($c['description']??null),'priority'=>(string)($p['priority']??$c['priority']??'normal'),'status'=>(string)($p['status']??$c['status']??'open'),'due_at'=>array_key_exists('due_at',$p)?(($p['due_at']??'')===''?null:(string)$p['due_at']):($c['due_at']??null),'completed_at'=>$c['completed_at']??null,'proof_note'=>array_key_exists('proof_note',$p)?(($p['proof_note']??'')===''?null:trim((string)$p['proof_note'])):($c['proof_note']??null),'proof_file_path'=>array_key_exists('proof_file_path',$p)?(($p['proof_file_path']??'')===''?null:trim((string)$p['proof_file_path'])):($c['proof_file_path']??null)]; }
}
