<?php
namespace App\Services\Operation;
use App\Core\BaseService; use App\Exceptions\ConflictApiException; use App\Exceptions\NotFoundApiException; use App\Exceptions\TenantAccessDeniedException; use App\Libraries\ListQuery; use App\Models\VehicleAccessListModel; use Config\Database;
class VehicleAccessListService extends BaseService
{
    public function __construct(private readonly VehicleAccessListModel $model = new VehicleAccessListModel()){ parent::__construct(); }
    public function list(array $query): array { $q=ListQuery::normalize($query,['sortable'=>['id','plate_number','list_type','status','created_at'],'filterable'=>['site_id','unit_id','list_type','status']]); $b=$this->model->builder()->select('*')->where('deleted_at',null); foreach($q['filters'] as $f=>$v){$b->where($f,$v);} if($q['search']!==''){$b->like('plate_number',$q['search']);} $t=(int)$b->countAllResults(false); $i=$b->orderBy($q['sort'],$q['direction'])->limit($q['per_page'],($q['page']-1)*$q['per_page'])->get()->getResultArray(); return ListQuery::envelope($q['page'],$q['per_page'],$t,$i);}
    public function show(int $id): array { $this->assertAccessible($id); $r=$this->model->tenantFind($id); if(!is_array($r)){throw new NotFoundApiException('Vehicle access kaydi bulunamadi');} return $r; }
    public function create(array $p): array { $d=$this->normalize($p); $this->assertScope($d['site_id'],$d['unit_id']); $this->assertDuplicateActive($d['site_id'],$d['plate_number'],$d['list_type'],null); $this->model->insert($d,true); $id=(int)$this->model->getInsertID(); $c=$this->show($id); $this->audit('security.vehicle_access_list.create.success',['entity_type'=>'vehicle_access_list','entity_id'=>$id,'new_values'=>$c]); return $c; }
    public function update(int $id,array $p): array { $old=$this->show($id); $d=$this->normalize($p,$old); $this->assertScope((int)$d['site_id'],$d['unit_id']!==null?(int)$d['unit_id']:null); $this->assertDuplicateActive((int)$d['site_id'],(string)$d['plate_number'],(string)$d['list_type'],$id); $this->model->update($id,$d); $n=$this->show($id); $this->audit('security.vehicle_access_list.update.success',['entity_type'=>'vehicle_access_list','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function delete(int $id): void { $old=$this->show($id); $this->model->delete($id); $this->audit('security.vehicle_access_list.delete.success',['entity_type'=>'vehicle_access_list','entity_id'=>$id,'old_values'=>$old]); }
    public function isBlacklisted(int $siteId, ?string $plate): bool { if($plate===null||$plate===''){return false;} $p=$this->normalizePlate($plate); $row=$this->model->builder()->select('id')->where('site_id',$siteId)->where('plate_number',$p)->where('list_type','blacklist')->where('status','active')->where('deleted_at',null)->get(1)->getRowArray(); return $row!==null; }
    /** @return array<string,mixed> */ private function normalize(array $p,array $c=[]): array { return ['site_id'=>(int)($p['site_id']??$c['site_id']??0),'unit_id'=>array_key_exists('unit_id',$p)?($p['unit_id']===''||$p['unit_id']===null?null:(int)$p['unit_id']):($c['unit_id']??null),'plate_number'=>$this->normalizePlate($p['plate_number']??$c['plate_number']??''),'list_type'=>(string)($p['list_type']??$c['list_type']??''),'reason'=>array_key_exists('reason',$p)?(($p['reason']??'')===''?null:(string)$p['reason']):($c['reason']??null),'status'=>(string)($p['status']??$c['status']??'active')]; }
    private function normalizePlate(mixed $plate): string { return strtoupper(str_replace(' ','',trim((string)$plate))); }
    private function assertScope(int $siteId,?int $unitId): void { $db=Database::connect(); $ctx=(int)(service('request')->company_id??0); $s=$db->table('sites')->where('id',$siteId)->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($s)){throw new NotFoundApiException('Site bulunamadi');} if($ctx>0&&(int)$s['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} if($unitId!==null){$u=$db->table('units')->where('id',$unitId)->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($u)){throw new NotFoundApiException('Unit bulunamadi');} if((int)$u['site_id']!==$siteId){throw new ConflictApiException('unit/site uyumsuz');} if($ctx>0&&(int)$u['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');}} }
    private function assertDuplicateActive(int $siteId,string $plate,string $listType,?int $exceptId): void { $b=$this->model->builder()->select('id')->where('site_id',$siteId)->where('plate_number',$plate)->where('list_type',$listType)->where('status','active')->where('deleted_at',null); if($exceptId!==null){$b->where('id !=',$exceptId);} if($b->get(1)->getRowArray()!==null){throw new ConflictApiException('Ayni site+plate+list_type icin aktif duplicate kayit olamaz');} }
    private function assertAccessible(int $id): void { $r=Database::connect()->table('vehicle_access_lists')->where('id',$id)->get(1)->getRowArray(); if(!is_array($r)||($r['deleted_at']??null)!==null){throw new NotFoundApiException('Vehicle access kaydi bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0&&(int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} }
}
