<?php
namespace App\Services\Operation;
use App\Core\BaseService; use App\Exceptions\ConflictApiException; use App\Exceptions\NotFoundApiException; use App\Exceptions\TenantAccessDeniedException; use App\Libraries\ListQuery; use App\Models\VisitorInviteModel; use Config\Database; use Throwable;
class VisitorInviteService extends BaseService
{
    public function __construct(private readonly VisitorInviteModel $model = new VisitorInviteModel()){ parent::__construct(); }
    public function list(array $query): array { $q=ListQuery::normalize($query,['sortable'=>['id','valid_from','valid_until','status','created_at'],'filterable'=>['site_id','unit_id','status']]); $b=$this->model->builder()->select('*')->where('deleted_at',null); foreach($q['filters'] as $f=>$v){$b->where($f,$v);} if($q['search']!==''){$b->groupStart()->like('visitor_name',$q['search'])->orLike('invite_code',$q['search'])->groupEnd();} $t=(int)$b->countAllResults(false); $i=$b->orderBy($q['sort'],$q['direction'])->limit($q['per_page'],($q['page']-1)*$q['per_page'])->get()->getResultArray(); return ListQuery::envelope($q['page'],$q['per_page'],$t,$i);}
    public function show(int $id): array { $this->assertAccessible($id); $r=$this->model->tenantFind($id); if(!is_array($r)){throw new NotFoundApiException('Invite bulunamadi');} return $r; }
    public function create(array $payload): array { $this->assertSiteUnitResident((int)$payload['site_id'],(int)$payload['unit_id'],isset($payload['resident_profile_id'])?(int)$payload['resident_profile_id']:null); $from=(string)$payload['valid_from']; $until=(string)$payload['valid_until']; if(strtotime($until)<strtotime($from)){throw new ConflictApiException('valid_until valid_fromtan kucuk olamaz');} $maxUses=(int)($payload['max_uses']??1); if($maxUses<1){throw new ConflictApiException('max_uses 1den kucuk olamaz');} $code=$this->generateCode(); $plate=$this->normalizePlate($payload['vehicle_plate']??null); $ok=false; $attempt=0; while(!$ok && $attempt<5){$attempt++; try{$this->model->insert(['site_id'=>(int)$payload['site_id'],'unit_id'=>(int)$payload['unit_id'],'resident_profile_id'=>$payload['resident_profile_id']??null,'invite_code'=>$code,'visitor_name'=>(string)$payload['visitor_name'],'visitor_phone'=>$payload['visitor_phone']??null,'vehicle_plate'=>$plate,'valid_from'=>$from,'valid_until'=>$until,'max_uses'=>$maxUses,'used_count'=>0,'status'=>'active','notes'=>$payload['notes']??null],true);$ok=true;}catch(Throwable $e){$m=strtolower($e->getMessage()); if(!str_contains($m,'duplicate')&&!str_contains($m,'unique')){throw $e;} $code=$this->generateCode();}} if(!$ok){throw new ConflictApiException('invite_code uretilemedi');} $id=(int)$this->model->getInsertID(); $c=$this->show($id); $this->audit('security.visitor_invite.create.success',['entity_type'=>'visitor_invite','entity_id'=>$id,'new_values'=>$c]); return $c; }
    public function cancel(int $id): array { $old=$this->show($id); if((string)$old['status']!=='active'){throw new ConflictApiException('Sadece active invite cancel edilir');} $this->model->update($id,['status'=>'cancelled']); $n=$this->show($id); $this->audit('security.visitor_invite.cancel.success',['entity_type'=>'visitor_invite','entity_id'=>$id,'old_values'=>$old,'new_values'=>$n]); return $n; }
    public function useInviteForCheckIn(int $id): array { $row=$this->show($id); if((string)$row['status']!=='active'){throw new ConflictApiException('Invite active degil');} $now=time(); if($now<strtotime((string)$row['valid_from']) || $now>strtotime((string)$row['valid_until'])){throw new ConflictApiException('Invite tarih araligi disinda');} if((int)$row['used_count']>=(int)$row['max_uses']){throw new ConflictApiException('Invite kullanim limiti dolmus');} $newUsed=(int)$row['used_count']+1; $newStatus=$newUsed>=(int)$row['max_uses']?'used':'active'; $this->model->update((int)$row['id'],['used_count'=>$newUsed,'status'=>$newStatus]); return $this->show((int)$row['id']); }
    /** @return array<string,mixed> */
    public function lockForCheckIn(int $id): array
    {
        $ctx=(int)(service('request')->company_id??0);
        $row=Database::connect()->query(
            "SELECT * FROM visitor_invites WHERE id = ? AND deleted_at IS NULL FOR UPDATE",
            [$id]
        )->getRowArray();
        if(!is_array($row)){throw new NotFoundApiException('Invite bulunamadi');}
        if($ctx>0 && (int)$row['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');}
        return $row;
    }
    public function updateUsageAfterLock(int $id, int $usedCount, string $status): void
    {
        $this->model->update($id, ['used_count' => $usedCount, 'status' => $status]);
    }
    private function assertSiteUnitResident(int $siteId,int $unitId,?int $residentId): void { $db=Database::connect(); $ctx=(int)(service('request')->company_id??0); $s=$db->table('sites')->where('id',$siteId)->where('deleted_at',null)->get(1)->getRowArray(); $u=$db->table('units')->where('id',$unitId)->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($s)||!is_array($u)){throw new NotFoundApiException('Site veya unit bulunamadi');} if((int)$u['site_id']!==$siteId){throw new ConflictApiException('unit/site uyumsuz');} if($ctx>0&&((int)$s['company_id']!==$ctx||(int)$u['company_id']!==$ctx)){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} if($residentId!==null){$r=$db->table('resident_profiles')->where('id',$residentId)->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($r)){throw new NotFoundApiException('Resident bulunamadi');} if($ctx>0&&(int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');} $occ=$db->table('unit_occupancies')->where('unit_id',$unitId)->where('resident_profile_id',$residentId)->where('status','active')->where('deleted_at',null)->get(1)->getRowArray(); if(!is_array($occ)){throw new ConflictApiException('resident/unit aktif occupancy yok');}} }
    private function assertAccessible(int $id): void { $r=Database::connect()->table('visitor_invites')->where('id',$id)->get(1)->getRowArray(); if(!is_array($r)||($r['deleted_at']??null)!==null){throw new NotFoundApiException('Invite bulunamadi');} $ctx=(int)(service('request')->company_id??0); if($ctx>0&&(int)$r['company_id']!==$ctx){throw new TenantAccessDeniedException('Cross-tenant erisim engellendi');}}
    private function generateCode(): string { return 'INV-'.date('YmdHis').'-'.strtoupper(substr(bin2hex(random_bytes(3)),0,6)); }
    public function normalizePlate(mixed $plate): ?string { if($plate===null){return null;} $p=strtoupper(str_replace(' ','',trim((string)$plate))); return $p===''?null:$p; }
}
